% Source code generated with Caramel.
-module(day_2).
-export_type([password_req/0]).
-export_type([position_counter/0]).
-export_type([validation_result/0]).

-export([count_all/2]).
-export([count_min_max/2]).
-export([count_valid/3]).
-export([is_in_position/2]).
-export([run/0]).

-type password_req() :: #{ letter => binary()
                         , min => integer()
                         , max => integer()
                         }.

-type validation_result() :: {valid, integer()}
                           | {invalid, integer()}
                           .

-type position_counter() :: found_first
                          | found_last
                          | not_found
                          | too_many
                          .

-spec count_min_max(password_req(), binary()) -> validation_result().
count_min_max(#{ letter := Letter, min := Min, max := Max }, Pwd) ->
  Parts = binary:bin_to_list(Pwd),
  Result = lists:foldl(fun
  (C, Acc) ->
  case erlang:'=:='(Letter, binary:list_to_bin([C | []])) of
    true -> erlang:'+'(Acc, 1);
    false -> Acc
  end
end, 0, Parts),
  case erlang:'and'(erlang:'>='(Result, Min), erlang:'=<'(Result, Max)) of
    true -> {valid, Result};
    false -> {invalid, Result}
  end.

-spec is_in_position(password_req(), binary()) -> validation_result().
is_in_position(#{ letter := Letter, min := Min, max := Max }, Pwd) ->
  Parts = binary:bin_to_list(Pwd),
  {Result, Idx} = lists:foldl(fun
  (C, {Counter, Idx}) ->
  Same_char = erlang:'=:='(Letter, binary:list_to_bin([C | []])),
  case Counter of
    not_found -> case erlang:'and'(erlang:'=:='(Idx, Min), Same_char) of
  true -> {found_first, erlang:'+'(Idx, 1)};
  false -> case erlang:'and'(erlang:'=:='(Idx, Max), Same_char) of
  true -> {found_last, erlang:'+'(Idx, 1)};
  false -> {not_found, erlang:'+'(Idx, 1)}
end
end;
    found_first -> case erlang:'and'(erlang:'=:='(Idx, Max), Same_char) of
  true -> {too_many, 0};
  false -> {found_first, erlang:'+'(Idx, 1)}
end;
    found_last -> case erlang:'and'(erlang:'=:='(Idx, Min), Same_char) of
  true -> {too_many, 0};
  false -> {found_last, erlang:'+'(Idx, 1)}
end;
    too_many -> {too_many, 0}
  end
end, {not_found, 1}, Parts),
  case Result of
    found_first -> {valid, Idx};
    found_last -> {valid, Idx};
    _ -> {invalid, 0}
  end.

-spec count_valid(A, list(B), fun((A, B) -> validation_result())) -> integer().
count_valid(Req, Pwds, Run_validation) ->
  Results = lists:map(fun
  (Pwd) -> Run_validation(Req, Pwd)
end, Pwds),
  lists:foldl(fun
  (R, Acc) ->
  case R of
    {valid, _} -> erlang:'+'(Acc, 1);
    _ -> Acc
  end
end, 0, Results).

-spec count_all(fun((A, B) -> validation_result()), list({A, list(B)})) -> integer().
count_all(Validation, Data) -> lists:foldl(fun
  ({R, Pwds}, Acc) -> erlang:'+'(count_valid(R, Pwds, Validation), Acc)
end, 0, Data).

-spec run() -> list(option:t(integer())).
run() ->
  Data = [{#{ letter => <<"s">>
 , min => 3
 , max => 6
 }, [<<"ssdsssss">> | []]} | [{#{ letter => <<"f">>
 , min => 17
 , max => 19
 }, [<<"cnffsfffzhfnsffttms">> | []]} | [{#{ letter => <<"c">>
 , min => 8
 , max => 11
 }, [<<"tzvtwncnwvwttp">> | []]} | [{#{ letter => <<"r">>
 , min => 8
 , max => 10
 }, [<<"rwrrtrvttrrrr">> | []]} | [{#{ letter => <<"p">>
 , min => 1
 , max => 2
 }, [<<"zhpjph">> | []]} | [{#{ letter => <<"l">>
 , min => 4
 , max => 6
 }, [<<"pldnxv">> | []]} | [{#{ letter => <<"k">>
 , min => 2
 , max => 12
 }, [<<"kkktrkwrbtck">> | []]} | [{#{ letter => <<"t">>
 , min => 14
 , max => 15
 }, [<<"tttttttttttnztttg">> | []]} | [{#{ letter => <<"g">>
 , min => 1
 , max => 3
 }, [<<"dgxg">> | []]} | [{#{ letter => <<"c">>
 , min => 4
 , max => 7
 }, [<<"tmxbccmcvgpp">> | []]} | [{#{ letter => <<"r">>
 , min => 2
 , max => 16
 }, [<<"rrrrrrrrrrrrrrrrr">> | []]} | [{#{ letter => <<"b">>
 , min => 10
 , max => 11
 }, [<<"bbblxbbrbbbblgwcxj">> | []]} | [{#{ letter => <<"s">>
 , min => 1
 , max => 7
 }, [<<"ssshzwpss">> | []]} | [{#{ letter => <<"k">>
 , min => 7
 , max => 13
 }, [<<"kkzkvgkdqskktkkkkk">> | []]} | [{#{ letter => <<"l">>
 , min => 1
 , max => 3
 }, [<<"wjldclpl">> | []]} | [{#{ letter => <<"n">>
 , min => 15
 , max => 17
 }, [<<"tqcsxnwhfnlmpcnjnlsn">> | []]} | [{#{ letter => <<"m">>
 , min => 8
 , max => 9
 }, [<<"mscmmxmkm">> | []]} | [{#{ letter => <<"n">>
 , min => 3
 , max => 4
 }, [<<"fngn">> | []]} | [{#{ letter => <<"g">>
 , min => 14
 , max => 15
 }, [<<"ggrbggglmktgvjg">> | []]} | [{#{ letter => <<"p">>
 , min => 5
 , max => 6
 }, [<<"ppppvxpp">> | []]} | [{#{ letter => <<"b">>
 , min => 4
 , max => 7
 }, [<<"gbbbrbqbwbfjqjg">> | []]} | [{#{ letter => <<"s">>
 , min => 8
 , max => 12
 }, [<<"vssssnsssjsssjsjs">> | []]} | [{#{ letter => <<"b">>
 , min => 6
 , max => 11
 }, [<<"bbbbbbtbbjdbbbb">> | []]} | [{#{ letter => <<"d">>
 , min => 16
 , max => 17
 }, [<<"dddqdmdqdddsdqbmd">> | []]} | [{#{ letter => <<"d">>
 , min => 18
 , max => 20
 }, [<<"bsddtgwddddddzdzdbdd">> | []]} | [{#{ letter => <<"c">>
 , min => 10
 , max => 11
 }, [<<"cccpcccccrkc">> | []]} | [{#{ letter => <<"d">>
 , min => 3
 , max => 8
 }, [<<"hddccvldwdthrc">> | []]} | [{#{ letter => <<"f">>
 , min => 7
 , max => 13
 }, [<<"ftmwxpcsfxzqv">> | []]} | [{#{ letter => <<"w">>
 , min => 12
 , max => 17
 }, [<<"wwfwwwtwwwwwwwwwww">> | []]} | [{#{ letter => <<"b">>
 , min => 9
 , max => 10
 }, [<<"bkbbbnbrsblvbrbpgb">> | []]} | [{#{ letter => <<"g">>
 , min => 15
 , max => 16
 }, [<<"ggggggggggggggggg">> | []]} | [{#{ letter => <<"v">>
 , min => 2
 , max => 9
 }, [<<"rnnvvwrvvvvvjvlr">> | []]} | [{#{ letter => <<"k">>
 , min => 4
 , max => 5
 }, [<<"qkkjwmkk">> | []]} | [{#{ letter => <<"v">>
 , min => 3
 , max => 8
 }, [<<"vmkvhvvvwvnpv">> | []]} | [{#{ letter => <<"v">>
 , min => 5
 , max => 8
 }, [<<"vgvvvvvf">> | []]} | [{#{ letter => <<"h">>
 , min => 6
 , max => 11
 }, [<<"jsngtkbnqhwthvhhhnh">> | []]} | [{#{ letter => <<"j">>
 , min => 2
 , max => 4
 }, [<<"jjjjj">> | []]} | [{#{ letter => <<"j">>
 , min => 1
 , max => 14
 }, [<<"jjjjjjjjjjjjjnjjj">> | []]} | [{#{ letter => <<"q">>
 , min => 4
 , max => 7
 }, [<<"wqqxnfq">> | []]} | [{#{ letter => <<"v">>
 , min => 16
 , max => 17
 }, [<<"vvvvvvvvvndvvvvjqv">> | []]} | [{#{ letter => <<"q">>
 , min => 2
 , max => 6
 }, [<<"gqqqqxqqqqqqqqqq">> | []]} | [{#{ letter => <<"x">>
 , min => 4
 , max => 7
 }, [<<"xxxjxxcxx">> | []]} | [{#{ letter => <<"m">>
 , min => 2
 , max => 7
 }, [<<"wmhzkmj">> | []]} | [{#{ letter => <<"l">>
 , min => 6
 , max => 10
 }, [<<"wlllnlllllllll">> | []]} | [{#{ letter => <<"g">>
 , min => 7
 , max => 9
 }, [<<"jkzqgxgbt">> | []]} | [{#{ letter => <<"f">>
 , min => 7
 , max => 8
 }, [<<"fffffflf">> | []]} | [{#{ letter => <<"j">>
 , min => 3
 , max => 6
 }, [<<"dlndzj">> | []]} | [{#{ letter => <<"t">>
 , min => 9
 , max => 12
 }, [<<"nttttttttttqt">> | []]} | [{#{ letter => <<"b">>
 , min => 3
 , max => 8
 }, [<<"pbnlbbbbbbbbbj">> | []]} | [{#{ letter => <<"t">>
 , min => 2
 , max => 8
 }, [<<"tjbftttdttt">> | []]} | [{#{ letter => <<"j">>
 , min => 4
 , max => 5
 }, [<<"pvjjg">> | []]} | [{#{ letter => <<"j">>
 , min => 2
 , max => 6
 }, [<<"jjksfb">> | []]} | [{#{ letter => <<"c">>
 , min => 2
 , max => 4
 }, [<<"hccc">> | []]} | [{#{ letter => <<"m">>
 , min => 5
 , max => 7
 }, [<<"mmnmmwzmmjmxb">> | []]} | [{#{ letter => <<"d">>
 , min => 6
 , max => 8
 }, [<<"cddmkdqdkpqh">> | []]} | [{#{ letter => <<"b">>
 , min => 6
 , max => 13
 }, [<<"ljwdhbbfzqjbz">> | []]} | [{#{ letter => <<"t">>
 , min => 11
 , max => 16
 }, [<<"ttttttttttjctltnt">> | []]} | [{#{ letter => <<"c">>
 , min => 3
 , max => 4
 }, [<<"xcgc">> | []]} | [{#{ letter => <<"p">>
 , min => 8
 , max => 9
 }, [<<"gpvpdpwqpwsppppp">> | []]} | [{#{ letter => <<"z">>
 , min => 3
 , max => 4
 }, [<<"rpvzzwfjzlkwhss">> | []]} | [{#{ letter => <<"q">>
 , min => 9
 , max => 10
 }, [<<"jhqgdqgqrqqnqqlcqqb">> | []]} | [{#{ letter => <<"z">>
 , min => 9
 , max => 10
 }, [<<"zzlzzpzzzsznzzz">> | []]} | [{#{ letter => <<"q">>
 , min => 5
 , max => 7
 }, [<<"lmmqbhqzq">> | []]} | [{#{ letter => <<"l">>
 , min => 9
 , max => 10
 }, [<<"llllllqpcqfjjcl">> | []]} | [{#{ letter => <<"l">>
 , min => 12
 , max => 13
 }, [<<"llllllllxlllllll">> | []]} | [{#{ letter => <<"z">>
 , min => 3
 , max => 5
 }, [<<"vzzzd">> | []]} | [{#{ letter => <<"f">>
 , min => 4
 , max => 7
 }, [<<"ffffffvff">> | []]} | [{#{ letter => <<"f">>
 , min => 7
 , max => 8
 }, [<<"fkffffxfmn">> | []]} | [{#{ letter => <<"x">>
 , min => 14
 , max => 16
 }, [<<"xxxxxxxxxxxxxtxnx">> | []]} | [{#{ letter => <<"t">>
 , min => 2
 , max => 10
 }, [<<"gcbdbqmccktp">> | []]} | [{#{ letter => <<"x">>
 , min => 2
 , max => 3
 }, [<<"nxzd">> | []]} | [{#{ letter => <<"q">>
 , min => 3
 , max => 8
 }, [<<"qqtxgnqgf">> | []]} | [{#{ letter => <<"h">>
 , min => 9
 , max => 17
 }, [<<"hhhvhhhhhhqhhhphhhd">> | []]} | [{#{ letter => <<"v">>
 , min => 8
 , max => 9
 }, [<<"vvvvvvvvvv">> | []]} | [{#{ letter => <<"p">>
 , min => 2
 , max => 4
 }, [<<"pctjppppjbm">> | []]} | [{#{ letter => <<"c">>
 , min => 2
 , max => 14
 }, [<<"frcgcscqgdgjzc">> | []]} | [{#{ letter => <<"n">>
 , min => 2
 , max => 3
 }, [<<"xzjnm">> | []]} | [{#{ letter => <<"k">>
 , min => 9
 , max => 10
 }, [<<"hkrkkkbhkkkkkk">> | []]} | [{#{ letter => <<"r">>
 , min => 18
 , max => 19
 }, [<<"rrrrrrrrrrrrrrrrrrh">> | []]} | [{#{ letter => <<"d">>
 , min => 13
 , max => 15
 }, [<<"bddddddmddgwddn">> | []]} | [{#{ letter => <<"k">>
 , min => 1
 , max => 6
 }, [<<"bkhxkkkng">> | []]} | [{#{ letter => <<"l">>
 , min => 8
 , max => 10
 }, [<<"dllmllqlmllll">> | []]} | [{#{ letter => <<"q">>
 , min => 4
 , max => 5
 }, [<<"qqwwgqqqq">> | []]} | [{#{ letter => <<"r">>
 , min => 1
 , max => 11
 }, [<<"jrrrcrbrksrb">> | []]} | [{#{ letter => <<"w">>
 , min => 10
 , max => 12
 }, [<<"ggwwwwwwtrwpzlwxbww">> | []]} | [{#{ letter => <<"z">>
 , min => 5
 , max => 6
 }, [<<"zzzkzs">> | []]} | [{#{ letter => <<"z">>
 , min => 9
 , max => 19
 }, [<<"zgzkzzzgddzzzzzzzzzk">> | []]} | [{#{ letter => <<"b">>
 , min => 18
 , max => 19
 }, [<<"bbbbbbbbbblbbbbbbvx">> | []]} | [{#{ letter => <<"g">>
 , min => 2
 , max => 7
 }, [<<"jzhkwgd">> | []]} | [{#{ letter => <<"j">>
 , min => 2
 , max => 4
 }, [<<"jjjf">> | []]} | [{#{ letter => <<"m">>
 , min => 14
 , max => 16
 }, [<<"mmmmmmmmmmmmmmmx">> | []]} | [{#{ letter => <<"c">>
 , min => 7
 , max => 12
 }, [<<"wfpscbrrxsssccbwg">> | []]} | [{#{ letter => <<"q">>
 , min => 17
 , max => 18
 }, [<<"qqqxqqqqqqqqqqqqnw">> | []]} | [{#{ letter => <<"k">>
 , min => 10
 , max => 13
 }, [<<"kkkkkkkkkckkkk">> | []]} | [{#{ letter => <<"d">>
 , min => 8
 , max => 9
 }, [<<"dddddddtd">> | []]} | [{#{ letter => <<"b">>
 , min => 7
 , max => 11
 }, [<<"nbbbfmbbxtbbpbxcz">> | []]} | [{#{ letter => <<"p">>
 , min => 2
 , max => 6
 }, [<<"pppqpp">> | []]} | [{#{ letter => <<"s">>
 , min => 2
 , max => 8
 }, [<<"shqplnxs">> | []]} | [{#{ letter => <<"z">>
 , min => 3
 , max => 6
 }, [<<"lzzzztszsvrw">> | []]} | [{#{ letter => <<"b">>
 , min => 2
 , max => 9
 }, [<<"sqxpbbtbbb">> | []]} | [{#{ letter => <<"f">>
 , min => 2
 , max => 5
 }, [<<"cjffp">> | []]} | [{#{ letter => <<"l">>
 , min => 2
 , max => 7
 }, [<<"lrllllll">> | []]} | [{#{ letter => <<"t">>
 , min => 1
 , max => 7
 }, [<<"ttttttt">> | []]} | [{#{ letter => <<"p">>
 , min => 3
 , max => 4
 }, [<<"vplp">> | []]} | [{#{ letter => <<"p">>
 , min => 9
 , max => 10
 }, [<<"zppppkrpsp">> | []]} | [{#{ letter => <<"j">>
 , min => 1
 , max => 4
 }, [<<"ttjjsqmt">> | []]} | [{#{ letter => <<"c">>
 , min => 2
 , max => 3
 }, [<<"tmhc">> | []]} | [{#{ letter => <<"h">>
 , min => 6
 , max => 9
 }, [<<"hhfwshhhx">> | []]} | [{#{ letter => <<"p">>
 , min => 3
 , max => 4
 }, [<<"pppp">> | []]} | [{#{ letter => <<"k">>
 , min => 3
 , max => 5
 }, [<<"kkkmk">> | []]} | [{#{ letter => <<"d">>
 , min => 1
 , max => 8
 }, [<<"mddxdddxddd">> | []]} | [{#{ letter => <<"w">>
 , min => 8
 , max => 16
 }, [<<"twwwwjkwztwwgnwwwr">> | []]} | [{#{ letter => <<"p">>
 , min => 8
 , max => 9
 }, [<<"pppppppppp">> | []]} | [{#{ letter => <<"j">>
 , min => 15
 , max => 17
 }, [<<"jjjjjjjkjvjjzjjlgjjj">> | []]} | [{#{ letter => <<"n">>
 , min => 1
 , max => 8
 }, [<<"wnrnnnnnnnn">> | []]} | [{#{ letter => <<"p">>
 , min => 7
 , max => 10
 }, [<<"pckslpcxgbpcbf">> | []]} | [{#{ letter => <<"g">>
 , min => 6
 , max => 15
 }, [<<"mdlrdgtqgsgmdxf">> | []]} | [{#{ letter => <<"x">>
 , min => 11
 , max => 13
 }, [<<"xxxxxxxjxxxxdxxxxx">> | []]} | [{#{ letter => <<"n">>
 , min => 12
 , max => 14
 }, [<<"nnnnnnnnnnnmncn">> | []]} | [{#{ letter => <<"x">>
 , min => 1
 , max => 4
 }, [<<"xbxx">> | []]} | [{#{ letter => <<"k">>
 , min => 7
 , max => 10
 }, [<<"tdtbhkkkgh">> | []]} | [{#{ letter => <<"n">>
 , min => 5
 , max => 8
 }, [<<"nndnqnrqnn">> | []]} | [{#{ letter => <<"d">>
 , min => 5
 , max => 6
 }, [<<"dlnhdddd">> | []]} | [{#{ letter => <<"f">>
 , min => 4
 , max => 8
 }, [<<"gglffnxf">> | []]} | [{#{ letter => <<"g">>
 , min => 1
 , max => 4
 }, [<<"gddxfjtlgwzprgq">> | []]} | [{#{ letter => <<"m">>
 , min => 8
 , max => 9
 }, [<<"mwmlwmmmlgshmmdmm">> | []]} | [{#{ letter => <<"s">>
 , min => 3
 , max => 5
 }, [<<"zhsss">> | []]} | [{#{ letter => <<"k">>
 , min => 5
 , max => 13
 }, [<<"nbdskzrfjxkkk">> | []]} | [{#{ letter => <<"s">>
 , min => 15
 , max => 18
 }, [<<"sssssssssssnssssss">> | []]} | [{#{ letter => <<"j">>
 , min => 6
 , max => 13
 }, [<<"jvrjcjjjxdgfpwjf">> | []]} | [{#{ letter => <<"c">>
 , min => 4
 , max => 14
 }, [<<"qlslzpstbccpgrd">> | []]} | [{#{ letter => <<"s">>
 , min => 4
 , max => 6
 }, [<<"sssstss">> | []]} | [{#{ letter => <<"g">>
 , min => 5
 , max => 15
 }, [<<"gnjpssgpqmslgmgpx">> | []]} | [{#{ letter => <<"b">>
 , min => 3
 , max => 5
 }, [<<"mbpcktvnb">> | []]} | [{#{ letter => <<"c">>
 , min => 6
 , max => 7
 }, [<<"cccccrcc">> | []]} | [{#{ letter => <<"t">>
 , min => 7
 , max => 8
 }, [<<"ttzttttt">> | []]} | [{#{ letter => <<"c">>
 , min => 2
 , max => 3
 }, [<<"vchcd">> | []]} | [{#{ letter => <<"v">>
 , min => 11
 , max => 14
 }, [<<"vxvvvdqvvvvqvv">> | []]} | [{#{ letter => <<"q">>
 , min => 4
 , max => 8
 }, [<<"bqdqqqqcqq">> | []]} | [{#{ letter => <<"v">>
 , min => 1
 , max => 3
 }, [<<"vstccv">> | []]} | [{#{ letter => <<"b">>
 , min => 5
 , max => 9
 }, [<<"bbbbbbbbb">> | []]} | [{#{ letter => <<"f">>
 , min => 10
 , max => 12
 }, [<<"rfsfhfgxffff">> | []]} | [{#{ letter => <<"z">>
 , min => 4
 , max => 5
 }, [<<"zzzztp">> | []]} | [{#{ letter => <<"m">>
 , min => 5
 , max => 6
 }, [<<"mmmmmm">> | []]} | [{#{ letter => <<"m">>
 , min => 10
 , max => 11
 }, [<<"mmwmmmmmmmgmm">> | []]} | [{#{ letter => <<"t">>
 , min => 4
 , max => 6
 }, [<<"xsqmqdltktvhsqsrttqk">> | []]} | [{#{ letter => <<"j">>
 , min => 11
 , max => 13
 }, [<<"jjjjjxjjjjjjjjs">> | []]} | [{#{ letter => <<"x">>
 , min => 16
 , max => 19
 }, [<<"xxzxxxrxxvvxdxsjkxx">> | []]} | [{#{ letter => <<"t">>
 , min => 5
 , max => 7
 }, [<<"jmwqtpttlttlt">> | []]} | [{#{ letter => <<"r">>
 , min => 7
 , max => 8
 }, [<<"drwfrrblrrkrrzr">> | []]} | [{#{ letter => <<"z">>
 , min => 2
 , max => 16
 }, [<<"chbzzxwfzcfhzkzz">> | []]} | [{#{ letter => <<"b">>
 , min => 9
 , max => 11
 }, [<<"bbbbbbhbbdb">> | []]} | [{#{ letter => <<"n">>
 , min => 8
 , max => 10
 }, [<<"drcvnsxjfv">> | []]} | [{#{ letter => <<"s">>
 , min => 3
 , max => 5
 }, [<<"sswsxst">> | []]} | [{#{ letter => <<"v">>
 , min => 5
 , max => 13
 }, [<<"vvvvvvvvvvvvvvvvvv">> | []]} | [{#{ letter => <<"w">>
 , min => 3
 , max => 4
 }, [<<"kwww">> | []]} | [{#{ letter => <<"j">>
 , min => 4
 , max => 7
 }, [<<"zcjnjrjjjxj">> | []]} | [{#{ letter => <<"c">>
 , min => 10
 , max => 12
 }, [<<"jwwmqvlkrqcp">> | []]} | [{#{ letter => <<"r">>
 , min => 2
 , max => 6
 }, [<<"zrnfclvkdxtgnwprwjkp">> | []]} | [{#{ letter => <<"f">>
 , min => 12
 , max => 13
 }, [<<"tfrfskfrsskffvfwrfpn">> | []]} | [{#{ letter => <<"j">>
 , min => 18
 , max => 20
 }, [<<"jjjjjjljjjjjjjwjjjjr">> | []]} | [{#{ letter => <<"p">>
 , min => 8
 , max => 13
 }, [<<"pqppqknpppmpfpshhvpp">> | []]} | [{#{ letter => <<"t">>
 , min => 8
 , max => 19
 }, [<<"rsstqxpzttwtrbttqkgl">> | []]} | [{#{ letter => <<"k">>
 , min => 3
 , max => 4
 }, [<<"bkkfk">> | []]} | [{#{ letter => <<"s">>
 , min => 17
 , max => 18
 }, [<<"kqdbhcssbcsfddrpzs">> | []]} | [{#{ letter => <<"r">>
 , min => 3
 , max => 4
 }, [<<"rqkbrrlzfcrn">> | []]} | [{#{ letter => <<"t">>
 , min => 1
 , max => 3
 }, [<<"ttttt">> | []]} | [{#{ letter => <<"f">>
 , min => 9
 , max => 16
 }, [<<"fdcfqmwskqvbthtf">> | []]} | [{#{ letter => <<"b">>
 , min => 2
 , max => 3
 }, [<<"xwpbm">> | []]} | [{#{ letter => <<"b">>
 , min => 12
 , max => 17
 }, [<<"bbwbbbthbbpxhbbbbbbb">> | []]} | [{#{ letter => <<"f">>
 , min => 11
 , max => 20
 }, [<<"ffjvffffffzfffffffff">> | []]} | [{#{ letter => <<"w">>
 , min => 1
 , max => 2
 }, [<<"dtwt">> | []]} | [{#{ letter => <<"s">>
 , min => 4
 , max => 7
 }, [<<"qzpjsls">> | []]} | [{#{ letter => <<"m">>
 , min => 6
 , max => 15
 }, [<<"mmmmmmmmmmmmmmmm">> | []]} | [{#{ letter => <<"g">>
 , min => 7
 , max => 8
 }, [<<"ccgggggxg">> | []]} | [{#{ letter => <<"m">>
 , min => 10
 , max => 13
 }, [<<"mxmpfcqcmqmlcmmmjcm">> | []]} | [{#{ letter => <<"v">>
 , min => 6
 , max => 16
 }, [<<"vvvnvzwkchvpjrvv">> | []]} | [{#{ letter => <<"r">>
 , min => 15
 , max => 16
 }, [<<"rrrrnrxnrldrprrb">> | []]} | [{#{ letter => <<"p">>
 , min => 11
 , max => 12
 }, [<<"ppppppppppjd">> | []]} | [{#{ letter => <<"z">>
 , min => 4
 , max => 7
 }, [<<"hzzqzzgzkz">> | []]} | [{#{ letter => <<"v">>
 , min => 1
 , max => 14
 }, [<<"vvslgvqvvcxvvljvvtvv">> | []]} | [{#{ letter => <<"w">>
 , min => 8
 , max => 11
 }, [<<"wtwhwfwkwwhw">> | []]} | [{#{ letter => <<"c">>
 , min => 4
 , max => 6
 }, [<<"cccmctccdcczcccccc">> | []]} | [{#{ letter => <<"z">>
 , min => 2
 , max => 4
 }, [<<"kzrrzt">> | []]} | [{#{ letter => <<"v">>
 , min => 3
 , max => 4
 }, [<<"vvvmhxgs">> | []]} | [{#{ letter => <<"s">>
 , min => 8
 , max => 12
 }, [<<"ssssssssssskssssssss">> | []]} | [{#{ letter => <<"z">>
 , min => 2
 , max => 4
 }, [<<"rkzzz">> | []]} | [{#{ letter => <<"m">>
 , min => 6
 , max => 7
 }, [<<"mnmrmfbmm">> | []]} | [{#{ letter => <<"p">>
 , min => 8
 , max => 12
 }, [<<"bhphvpjfjpsj">> | []]} | [{#{ letter => <<"r">>
 , min => 4
 , max => 6
 }, [<<"rrqrrjrr">> | []]} | [{#{ letter => <<"t">>
 , min => 3
 , max => 6
 }, [<<"trttlth">> | []]} | [{#{ letter => <<"j">>
 , min => 4
 , max => 5
 }, [<<"jjjvgvj">> | []]} | [{#{ letter => <<"b">>
 , min => 9
 , max => 12
 }, [<<"lbbxlbbxkkbb">> | []]} | [{#{ letter => <<"d">>
 , min => 8
 , max => 9
 }, [<<"dddddddwm">> | []]} | [{#{ letter => <<"z">>
 , min => 14
 , max => 15
 }, [<<"fhdzzzgzbzvzdzz">> | []]} | [{#{ letter => <<"c">>
 , min => 8
 , max => 11
 }, [<<"cbccrbdwdccccsk">> | []]} | [{#{ letter => <<"t">>
 , min => 5
 , max => 6
 }, [<<"wttxtm">> | []]} | [{#{ letter => <<"f">>
 , min => 11
 , max => 14
 }, [<<"tbvfftkfffjfffffc">> | []]} | [{#{ letter => <<"b">>
 , min => 2
 , max => 3
 }, [<<"bbrb">> | []]} | [{#{ letter => <<"b">>
 , min => 3
 , max => 4
 }, [<<"brbwbb">> | []]} | [{#{ letter => <<"f">>
 , min => 12
 , max => 16
 }, [<<"ffkfffxfzfffffffl">> | []]} | [{#{ letter => <<"n">>
 , min => 11
 , max => 14
 }, [<<"nnnnnnnqgnsnbq">> | []]} | [{#{ letter => <<"z">>
 , min => 10
 , max => 13
 }, [<<"zzzzzzzzhzzzzzzz">> | []]} | [{#{ letter => <<"z">>
 , min => 2
 , max => 13
 }, [<<"qzrzddvglwfzqjqln">> | []]} | [{#{ letter => <<"n">>
 , min => 9
 , max => 12
 }, [<<"snnnnnnnnnjlnnnn">> | []]} | [{#{ letter => <<"l">>
 , min => 5
 , max => 9
 }, [<<"pqllllbvb">> | []]} | [{#{ letter => <<"z">>
 , min => 6
 , max => 13
 }, [<<"pszzmzzzzzzzz">> | []]} | [{#{ letter => <<"d">>
 , min => 5
 , max => 9
 }, [<<"ddddqdddd">> | []]} | [{#{ letter => <<"l">>
 , min => 9
 , max => 16
 }, [<<"llllllllxllllllsl">> | []]} | [{#{ letter => <<"w">>
 , min => 3
 , max => 10
 }, [<<"rfwwgwlwftcw">> | []]} | [{#{ letter => <<"t">>
 , min => 2
 , max => 6
 }, [<<"wphbtstkzxwntspptt">> | []]} | [{#{ letter => <<"j">>
 , min => 7
 , max => 14
 }, [<<"xchzzxmmjkggmxqrs">> | []]} | [{#{ letter => <<"f">>
 , min => 6
 , max => 8
 }, [<<"fffvxffffn">> | []]} | [{#{ letter => <<"h">>
 , min => 13
 , max => 14
 }, [<<"qhhhxhrhshhhhh">> | []]} | [{#{ letter => <<"q">>
 , min => 7
 , max => 8
 }, [<<"qqqqqqjwqqqqq">> | []]} | [{#{ letter => <<"l">>
 , min => 1
 , max => 3
 }, [<<"llslll">> | []]} | [{#{ letter => <<"f">>
 , min => 1
 , max => 7
 }, [<<"ftphbnfwwxzkfcsbr">> | []]} | [{#{ letter => <<"r">>
 , min => 5
 , max => 10
 }, [<<"rjrrrrhrrxrz">> | []]} | [{#{ letter => <<"p">>
 , min => 7
 , max => 9
 }, [<<"pppbplzph">> | []]} | [{#{ letter => <<"p">>
 , min => 5
 , max => 7
 }, [<<"ppppptpp">> | []]} | [{#{ letter => <<"t">>
 , min => 10
 , max => 11
 }, [<<"tttttttttjr">> | []]} | [{#{ letter => <<"h">>
 , min => 12
 , max => 13
 }, [<<"hhhqhhhhhhbzhhhgv">> | []]} | [{#{ letter => <<"z">>
 , min => 13
 , max => 14
 }, [<<"zzzzpzzzvzzzztz">> | []]} | [{#{ letter => <<"w">>
 , min => 11
 , max => 12
 }, [<<"wqwrwwwkwwdw">> | []]} | [{#{ letter => <<"z">>
 , min => 1
 , max => 11
 }, [<<"zzzzzzzzzxkzz">> | []]} | [{#{ letter => <<"k">>
 , min => 1
 , max => 4
 }, [<<"tkks">> | []]} | [{#{ letter => <<"x">>
 , min => 3
 , max => 6
 }, [<<"xxxtxdwxxnxxtfxxxwx">> | []]} | [{#{ letter => <<"z">>
 , min => 12
 , max => 15
 }, [<<"kzzzzzzzzzzzzzz">> | []]} | [{#{ letter => <<"k">>
 , min => 2
 , max => 16
 }, [<<"jdsqqmbdktthvxmk">> | []]} | [{#{ letter => <<"t">>
 , min => 10
 , max => 13
 }, [<<"ctttfqttzqjjtfsxn">> | []]} | [{#{ letter => <<"t">>
 , min => 4
 , max => 7
 }, [<<"tttwttk">> | []]} | [{#{ letter => <<"r">>
 , min => 1
 , max => 4
 }, [<<"zrrprrk">> | []]} | [{#{ letter => <<"v">>
 , min => 5
 , max => 9
 }, [<<"cvvwvkvwv">> | []]} | [{#{ letter => <<"v">>
 , min => 7
 , max => 9
 }, [<<"vvmvvvvvlwlwgwv">> | []]} | [{#{ letter => <<"q">>
 , min => 10
 , max => 14
 }, [<<"qqqqqqqqqqqqqq">> | []]} | [{#{ letter => <<"v">>
 , min => 5
 , max => 6
 }, [<<"vvvvvvv">> | []]} | [{#{ letter => <<"q">>
 , min => 2
 , max => 5
 }, [<<"cqqqqqqq">> | []]} | [{#{ letter => <<"b">>
 , min => 12
 , max => 13
 }, [<<"bbbbgbbbbbbqvbb">> | []]} | [{#{ letter => <<"v">>
 , min => 17
 , max => 19
 }, [<<"dhgcvvkrpwvtwvlvvrn">> | []]} | [{#{ letter => <<"h">>
 , min => 4
 , max => 6
 }, [<<"hhmmhhh">> | []]} | [{#{ letter => <<"g">>
 , min => 16
 , max => 18
 }, [<<"bgcggrgggggggggggg">> | []]} | [{#{ letter => <<"m">>
 , min => 2
 , max => 4
 }, [<<"mmtv">> | []]} | [{#{ letter => <<"m">>
 , min => 2
 , max => 9
 }, [<<"gmmmqmmlghmmkbmsqsmm">> | []]} | [{#{ letter => <<"f">>
 , min => 5
 , max => 6
 }, [<<"lfpffffpfhf">> | []]} | [{#{ letter => <<"t">>
 , min => 8
 , max => 9
 }, [<<"ttbttttwpt">> | []]} | [{#{ letter => <<"h">>
 , min => 7
 , max => 9
 }, [<<"hhhhchhhch">> | []]} | [{#{ letter => <<"h">>
 , min => 2
 , max => 4
 }, [<<"vnht">> | []]} | [{#{ letter => <<"k">>
 , min => 2
 , max => 3
 }, [<<"kkkqk">> | []]} | [{#{ letter => <<"c">>
 , min => 11
 , max => 13
 }, [<<"fhfcjkwxcfsqctc">> | []]} | [{#{ letter => <<"c">>
 , min => 10
 , max => 11
 }, [<<"cscscccvcqx">> | []]} | [{#{ letter => <<"k">>
 , min => 7
 , max => 9
 }, [<<"vkkkkxrlck">> | []]} | [{#{ letter => <<"g">>
 , min => 6
 , max => 7
 }, [<<"fgfrgdtkrmsgsg">> | []]} | [{#{ letter => <<"r">>
 , min => 6
 , max => 7
 }, [<<"rjrrkrrrt">> | []]} | [{#{ letter => <<"t">>
 , min => 8
 , max => 13
 }, [<<"ttttttttttttt">> | []]} | [{#{ letter => <<"g">>
 , min => 2
 , max => 9
 }, [<<"mnkkxttgm">> | []]} | [{#{ letter => <<"g">>
 , min => 3
 , max => 6
 }, [<<"ggggqlgng">> | []]} | [{#{ letter => <<"j">>
 , min => 5
 , max => 6
 }, [<<"lgjxgj">> | []]} | [{#{ letter => <<"n">>
 , min => 5
 , max => 7
 }, [<<"ngkknrh">> | []]} | [{#{ letter => <<"d">>
 , min => 1
 , max => 16
 }, [<<"dddddddddddddddpd">> | []]} | [{#{ letter => <<"p">>
 , min => 1
 , max => 7
 }, [<<"plpdvrswpppzcp">> | []]} | [{#{ letter => <<"n">>
 , min => 5
 , max => 14
 }, [<<"znnnlntlnnnnnjn">> | []]} | [{#{ letter => <<"w">>
 , min => 10
 , max => 11
 }, [<<"wwwwmwqwwwgwv">> | []]} | [{#{ letter => <<"g">>
 , min => 7
 , max => 8
 }, [<<"gggggggt">> | []]} | [{#{ letter => <<"m">>
 , min => 3
 , max => 8
 }, [<<"mmtmmdkncmqxqrz">> | []]} | [{#{ letter => <<"t">>
 , min => 3
 , max => 5
 }, [<<"ttrtnt">> | []]} | [{#{ letter => <<"z">>
 , min => 2
 , max => 3
 }, [<<"pdzscxrmmbpchktnz">> | []]} | [{#{ letter => <<"z">>
 , min => 1
 , max => 5
 }, [<<"ztcgllzvzzvcfvgzr">> | []]} | [{#{ letter => <<"l">>
 , min => 6
 , max => 8
 }, [<<"llltpkdsdkltcll">> | []]} | [{#{ letter => <<"h">>
 , min => 10
 , max => 13
 }, [<<"fhhhhcbhhchxc">> | []]} | [{#{ letter => <<"x">>
 , min => 14
 , max => 15
 }, [<<"xcpnxnxvbxxxbxx">> | []]} | [{#{ letter => <<"n">>
 , min => 9
 , max => 16
 }, [<<"nnnnnnnnwpncdnnnnn">> | []]} | [{#{ letter => <<"t">>
 , min => 4
 , max => 8
 }, [<<"ttbtwxlxhtkzwrrvc">> | []]} | [{#{ letter => <<"l">>
 , min => 4
 , max => 10
 }, [<<"lwzglkgkcwzwb">> | []]} | [{#{ letter => <<"t">>
 , min => 2
 , max => 3
 }, [<<"lstmttkttt">> | []]} | [{#{ letter => <<"f">>
 , min => 4
 , max => 6
 }, [<<"fhsfdf">> | []]} | [{#{ letter => <<"n">>
 , min => 4
 , max => 5
 }, [<<"nnnbns">> | []]} | [{#{ letter => <<"v">>
 , min => 1
 , max => 10
 }, [<<"tvvvvvvvvw">> | []]} | [{#{ letter => <<"r">>
 , min => 2
 , max => 13
 }, [<<"rtrrgqprprrbfrrrrr">> | []]} | [{#{ letter => <<"d">>
 , min => 7
 , max => 8
 }, [<<"cfwtbdsd">> | []]} | [{#{ letter => <<"g">>
 , min => 4
 , max => 5
 }, [<<"ggwgggg">> | []]} | [{#{ letter => <<"r">>
 , min => 4
 , max => 11
 }, [<<"nccrrfcxsnvkrrrz">> | []]} | [{#{ letter => <<"b">>
 , min => 1
 , max => 5
 }, [<<"bcqwbzbbtfbwb">> | []]} | [{#{ letter => <<"d">>
 , min => 8
 , max => 16
 }, [<<"dfddddddddzdddddtdd">> | []]} | [{#{ letter => <<"g">>
 , min => 3
 , max => 7
 }, [<<"ggggbdgggg">> | []]} | [{#{ letter => <<"r">>
 , min => 8
 , max => 9
 }, [<<"rlrrrrrrd">> | []]} | [{#{ letter => <<"n">>
 , min => 4
 , max => 5
 }, [<<"ntnnsn">> | []]} | [{#{ letter => <<"z">>
 , min => 7
 , max => 8
 }, [<<"zzzzzzww">> | []]} | [{#{ letter => <<"p">>
 , min => 1
 , max => 13
 }, [<<"vpppppnfcppqm">> | []]} | [{#{ letter => <<"s">>
 , min => 4
 , max => 8
 }, [<<"sqssxsss">> | []]} | [{#{ letter => <<"z">>
 , min => 2
 , max => 4
 }, [<<"bznt">> | []]} | [{#{ letter => <<"w">>
 , min => 5
 , max => 6
 }, [<<"swczww">> | []]} | [{#{ letter => <<"l">>
 , min => 3
 , max => 7
 }, [<<"lbvklllknbh">> | []]} | [{#{ letter => <<"g">>
 , min => 3
 , max => 4
 }, [<<"gbvgj">> | []]} | [{#{ letter => <<"w">>
 , min => 9
 , max => 10
 }, [<<"wwwwwwwtwwbww">> | []]} | [{#{ letter => <<"k">>
 , min => 7
 , max => 9
 }, [<<"pvkqmkkqllxktdz">> | []]} | [{#{ letter => <<"g">>
 , min => 6
 , max => 7
 }, [<<"bkgkggsfbgh">> | []]} | [{#{ letter => <<"j">>
 , min => 12
 , max => 13
 }, [<<"xjlxjkjjcdjbj">> | []]} | [{#{ letter => <<"x">>
 , min => 6
 , max => 7
 }, [<<"xxxxvgl">> | []]} | [{#{ letter => <<"x">>
 , min => 5
 , max => 13
 }, [<<"xpsxxtbbxfxwmnmbr">> | []]} | [{#{ letter => <<"g">>
 , min => 2
 , max => 4
 }, [<<"pxzp">> | []]} | [{#{ letter => <<"k">>
 , min => 4
 , max => 5
 }, [<<"qskgkkktfk">> | []]} | [{#{ letter => <<"w">>
 , min => 10
 , max => 12
 }, [<<"wjjxwswnwqwkdmbwwww">> | []]} | [{#{ letter => <<"m">>
 , min => 1
 , max => 9
 }, [<<"kmmlcmdbh">> | []]} | [{#{ letter => <<"x">>
 , min => 3
 , max => 6
 }, [<<"mxzqrlxn">> | []]} | [{#{ letter => <<"k">>
 , min => 4
 , max => 8
 }, [<<"rkrcltmkk">> | []]} | [{#{ letter => <<"x">>
 , min => 6
 , max => 11
 }, [<<"xfrjffvwdrpvkvgjz">> | []]} | [{#{ letter => <<"g">>
 , min => 9
 , max => 10
 }, [<<"ggggpkgcggggsg">> | []]} | [{#{ letter => <<"j">>
 , min => 7
 , max => 9
 }, [<<"jjgmjjbjjjj">> | []]} | [{#{ letter => <<"r">>
 , min => 2
 , max => 10
 }, [<<"rjrrrrrrrlr">> | []]} | [{#{ letter => <<"x">>
 , min => 4
 , max => 5
 }, [<<"xxxlxd">> | []]} | [{#{ letter => <<"r">>
 , min => 3
 , max => 4
 }, [<<"rzrnrr">> | []]} | [{#{ letter => <<"s">>
 , min => 1
 , max => 4
 }, [<<"ssslsssssss">> | []]} | [{#{ letter => <<"n">>
 , min => 2
 , max => 5
 }, [<<"nbtdnf">> | []]} | [{#{ letter => <<"l">>
 , min => 3
 , max => 5
 }, [<<"lfvlll">> | []]} | [{#{ letter => <<"z">>
 , min => 3
 , max => 9
 }, [<<"kcrjrrjvzjnzbvx">> | []]} | [{#{ letter => <<"j">>
 , min => 7
 , max => 12
 }, [<<"jjjjjjjjjjjmjj">> | []]} | [{#{ letter => <<"c">>
 , min => 4
 , max => 9
 }, [<<"cccgccxqm">> | []]} | [{#{ letter => <<"h">>
 , min => 2
 , max => 8
 }, [<<"pxjwgjlpd">> | []]} | [{#{ letter => <<"k">>
 , min => 13
 , max => 17
 }, [<<"kkkkkkkkkkkkvkkktkk">> | []]} | [{#{ letter => <<"j">>
 , min => 8
 , max => 13
 }, [<<"xjxjgjjjjjjlx">> | []]} | [{#{ letter => <<"t">>
 , min => 1
 , max => 5
 }, [<<"ttttg">> | []]} | [{#{ letter => <<"w">>
 , min => 2
 , max => 5
 }, [<<"wdwwfwwxwwnwwwwck">> | []]} | [{#{ letter => <<"n">>
 , min => 12
 , max => 13
 }, [<<"nnnnnnnnnnvpqnn">> | []]} | [{#{ letter => <<"g">>
 , min => 1
 , max => 3
 }, [<<"gtgg">> | []]} | [{#{ letter => <<"d">>
 , min => 5
 , max => 7
 }, [<<"dqddldd">> | []]} | [{#{ letter => <<"n">>
 , min => 4
 , max => 14
 }, [<<"hnxfhwfkvvnqzhz">> | []]} | [{#{ letter => <<"z">>
 , min => 17
 , max => 19
 }, [<<"zcdpstnzvtpvmzzcztz">> | []]} | [{#{ letter => <<"b">>
 , min => 5
 , max => 6
 }, [<<"bbmbbdcbw">> | []]} | [{#{ letter => <<"t">>
 , min => 4
 , max => 13
 }, [<<"ttqttcttqtfttttt">> | []]} | [{#{ letter => <<"l">>
 , min => 1
 , max => 2
 }, [<<"lvlklkc">> | []]} | [{#{ letter => <<"d">>
 , min => 11
 , max => 16
 }, [<<"ddddcdtdddwdrdddddd">> | []]} | [{#{ letter => <<"j">>
 , min => 3
 , max => 5
 }, [<<"xcnjfznjhqzj">> | []]} | [{#{ letter => <<"s">>
 , min => 1
 , max => 3
 }, [<<"ssssssrps">> | []]} | [{#{ letter => <<"w">>
 , min => 2
 , max => 4
 }, [<<"twzfrrgqjkcczjp">> | []]} | [{#{ letter => <<"d">>
 , min => 11
 , max => 12
 }, [<<"qvddkhdddskn">> | []]} | [{#{ letter => <<"t">>
 , min => 4
 , max => 5
 }, [<<"wtjttt">> | []]} | [{#{ letter => <<"t">>
 , min => 1
 , max => 4
 }, [<<"ptttldt">> | []]} | [{#{ letter => <<"z">>
 , min => 6
 , max => 8
 }, [<<"zzzzzdzhz">> | []]} | [{#{ letter => <<"d">>
 , min => 4
 , max => 8
 }, [<<"ddkdddddddd">> | []]} | [{#{ letter => <<"f">>
 , min => 6
 , max => 7
 }, [<<"ffffpfff">> | []]} | [{#{ letter => <<"j">>
 , min => 7
 , max => 9
 }, [<<"hzjspbsvjfgjtwd">> | []]} | [{#{ letter => <<"b">>
 , min => 3
 , max => 6
 }, [<<"bblkbb">> | []]} | [{#{ letter => <<"m">>
 , min => 6
 , max => 16
 }, [<<"qcmbmrsxdfwxmmnf">> | []]} | [{#{ letter => <<"l">>
 , min => 3
 , max => 4
 }, [<<"lxll">> | []]} | [{#{ letter => <<"g">>
 , min => 1
 , max => 5
 }, [<<"gzmgslb">> | []]} | [{#{ letter => <<"z">>
 , min => 8
 , max => 17
 }, [<<"mpxpgljtpcjwltmst">> | []]} | [{#{ letter => <<"b">>
 , min => 5
 , max => 8
 }, [<<"bbwbbbnkmbmhgbsbj">> | []]} | [{#{ letter => <<"f">>
 , min => 2
 , max => 3
 }, [<<"ffff">> | []]} | [{#{ letter => <<"s">>
 , min => 6
 , max => 9
 }, [<<"sssfsgsgsbstscdszhr">> | []]} | [{#{ letter => <<"v">>
 , min => 1
 , max => 2
 }, [<<"bsjwvvv">> | []]} | [{#{ letter => <<"k">>
 , min => 1
 , max => 2
 }, [<<"kkkkkkkkkkkkkkk">> | []]} | [{#{ letter => <<"h">>
 , min => 1
 , max => 2
 }, [<<"stxx">> | []]} | [{#{ letter => <<"k">>
 , min => 8
 , max => 9
 }, [<<"kgkckkwcmmtkkwkw">> | []]} | [{#{ letter => <<"p">>
 , min => 1
 , max => 18
 }, [<<"pppprzcpgpmpnppppz">> | []]} | [{#{ letter => <<"x">>
 , min => 1
 , max => 5
 }, [<<"qtcrxsggtdl">> | []]} | [{#{ letter => <<"j">>
 , min => 14
 , max => 17
 }, [<<"pwfvwzjsmtqcsjjgd">> | []]} | [{#{ letter => <<"w">>
 , min => 1
 , max => 13
 }, [<<"wxbvsfwfwkxwwvzg">> | []]} | [{#{ letter => <<"k">>
 , min => 2
 , max => 6
 }, [<<"kwqkkkk">> | []]} | [{#{ letter => <<"t">>
 , min => 2
 , max => 7
 }, [<<"vrztkcx">> | []]} | [{#{ letter => <<"k">>
 , min => 9
 , max => 13
 }, [<<"kkkkkkkrkkkkt">> | []]} | [{#{ letter => <<"w">>
 , min => 1
 , max => 2
 }, [<<"wrjxrxwwp">> | []]} | [{#{ letter => <<"m">>
 , min => 3
 , max => 11
 }, [<<"mwmjmmmmqlmmmmml">> | []]} | [{#{ letter => <<"c">>
 , min => 1
 , max => 6
 }, [<<"zcccccc">> | []]} | [{#{ letter => <<"h">>
 , min => 9
 , max => 10
 }, [<<"vhhntcjjhr">> | []]} | [{#{ letter => <<"z">>
 , min => 18
 , max => 19
 }, [<<"wszdzfjnvzbhrgzcgrz">> | []]} | [{#{ letter => <<"x">>
 , min => 11
 , max => 12
 }, [<<"xxxxxxxxxxwxxx">> | []]} | [{#{ letter => <<"b">>
 , min => 7
 , max => 11
 }, [<<"bvnbbbbjbnbbb">> | []]} | [{#{ letter => <<"r">>
 , min => 4
 , max => 14
 }, [<<"fbrxgtsbrbrrhrrdrr">> | []]} | [{#{ letter => <<"x">>
 , min => 15
 , max => 16
 }, [<<"xxxxxwxktpxkvxxb">> | []]} | [{#{ letter => <<"r">>
 , min => 1
 , max => 3
 }, [<<"rtqvmrzwnwmgxk">> | []]} | [{#{ letter => <<"s">>
 , min => 12
 , max => 14
 }, [<<"sfssfspctrskspqssss">> | []]} | [{#{ letter => <<"p">>
 , min => 5
 , max => 7
 }, [<<"ppppgppp">> | []]} | [{#{ letter => <<"n">>
 , min => 4
 , max => 5
 }, [<<"nnhtd">> | []]} | [{#{ letter => <<"d">>
 , min => 7
 , max => 14
 }, [<<"ddddddswbddmdr">> | []]} | [{#{ letter => <<"j">>
 , min => 5
 , max => 6
 }, [<<"jjjjjj">> | []]} | [{#{ letter => <<"d">>
 , min => 8
 , max => 12
 }, [<<"zjdddddddtnvdvdddd">> | []]} | [{#{ letter => <<"q">>
 , min => 1
 , max => 4
 }, [<<"rhrz">> | []]} | [{#{ letter => <<"c">>
 , min => 3
 , max => 17
 }, [<<"lnspcskfnggtqvxfc">> | []]} | [{#{ letter => <<"d">>
 , min => 7
 , max => 9
 }, [<<"lvxrkdwfc">> | []]} | [{#{ letter => <<"g">>
 , min => 5
 , max => 6
 }, [<<"gxggfkjmh">> | []]} | [{#{ letter => <<"k">>
 , min => 2
 , max => 7
 }, [<<"jkpsbcq">> | []]} | [{#{ letter => <<"p">>
 , min => 4
 , max => 12
 }, [<<"pcptjwccgppcp">> | []]} | [{#{ letter => <<"w">>
 , min => 5
 , max => 16
 }, [<<"wwwwwwwwwwwwwwwwww">> | []]} | [{#{ letter => <<"f">>
 , min => 3
 , max => 6
 }, [<<"rcmcffxgm">> | []]} | [{#{ letter => <<"t">>
 , min => 10
 , max => 14
 }, [<<"tttttmtwxwthvd">> | []]} | [{#{ letter => <<"v">>
 , min => 9
 , max => 11
 }, [<<"vvvvvvvvvvvvvv">> | []]} | [{#{ letter => <<"x">>
 , min => 4
 , max => 7
 }, [<<"xxclxxx">> | []]} | [{#{ letter => <<"z">>
 , min => 7
 , max => 10
 }, [<<"zzzzzvzzmnz">> | []]} | [{#{ letter => <<"t">>
 , min => 2
 , max => 3
 }, [<<"hcthfjxkh">> | []]} | [{#{ letter => <<"v">>
 , min => 1
 , max => 2
 }, [<<"xvxvk">> | []]} | [{#{ letter => <<"b">>
 , min => 8
 , max => 11
 }, [<<"bbbbbbblbbnb">> | []]} | [{#{ letter => <<"b">>
 , min => 6
 , max => 18
 }, [<<"qbjxjbrqfrwgdrzldbt">> | []]} | [{#{ letter => <<"v">>
 , min => 14
 , max => 16
 }, [<<"sprsxwphvvbvcvkv">> | []]} | [{#{ letter => <<"c">>
 , min => 11
 , max => 17
 }, [<<"dpwlccccmclbqzcptrc">> | []]} | [{#{ letter => <<"w">>
 , min => 13
 , max => 19
 }, [<<"wwwwwkwwwwwmwwzmvww">> | []]} | [{#{ letter => <<"m">>
 , min => 8
 , max => 14
 }, [<<"mdfvmpmrskvqcmvmddv">> | []]} | [{#{ letter => <<"v">>
 , min => 4
 , max => 13
 }, [<<"vvvvvvvvvgkvvvvvwvv">> | []]} | [{#{ letter => <<"g">>
 , min => 1
 , max => 3
 }, [<<"lgwqgg">> | []]} | [{#{ letter => <<"r">>
 , min => 1
 , max => 3
 }, [<<"rrrrzrr">> | []]} | [{#{ letter => <<"h">>
 , min => 2
 , max => 4
 }, [<<"hkrh">> | []]} | [{#{ letter => <<"h">>
 , min => 3
 , max => 6
 }, [<<"gwhzvhv">> | []]} | [{#{ letter => <<"x">>
 , min => 16
 , max => 19
 }, [<<"xxxxxxxxxxlxvxxxnxt">> | []]} | [{#{ letter => <<"t">>
 , min => 2
 , max => 3
 }, [<<"tttq">> | []]} | [{#{ letter => <<"w">>
 , min => 9
 , max => 13
 }, [<<"zkmpkfwwpwwwcw">> | []]} | [{#{ letter => <<"n">>
 , min => 7
 , max => 8
 }, [<<"nnjxnnnnbnhnr">> | []]} | [{#{ letter => <<"w">>
 , min => 5
 , max => 7
 }, [<<"ddzdwwww">> | []]} | [{#{ letter => <<"b">>
 , min => 11
 , max => 16
 }, [<<"bbbbbbbbbbbbbbbbb">> | []]} | [{#{ letter => <<"j">>
 , min => 2
 , max => 9
 }, [<<"wvtdzjzzb">> | []]} | [{#{ letter => <<"d">>
 , min => 3
 , max => 4
 }, [<<"dcbdd">> | []]} | [{#{ letter => <<"n">>
 , min => 3
 , max => 4
 }, [<<"gnng">> | []]} | [{#{ letter => <<"c">>
 , min => 5
 , max => 11
 }, [<<"fgcqcnqbcmv">> | []]} | [{#{ letter => <<"s">>
 , min => 13
 , max => 16
 }, [<<"nqssssssssxssskss">> | []]} | [{#{ letter => <<"b">>
 , min => 6
 , max => 9
 }, [<<"bjrdbbprb">> | []]} | [{#{ letter => <<"d">>
 , min => 3
 , max => 14
 }, [<<"jtdbmqqxsndhcdgm">> | []]} | [{#{ letter => <<"p">>
 , min => 10
 , max => 11
 }, [<<"pppppxpppxbp">> | []]} | [{#{ letter => <<"x">>
 , min => 8
 , max => 9
 }, [<<"xxdpxxhxq">> | []]} | [{#{ letter => <<"f">>
 , min => 5
 , max => 7
 }, [<<"ffffdkf">> | []]} | [{#{ letter => <<"z">>
 , min => 2
 , max => 9
 }, [<<"zzzzzjzdnzzzzzc">> | []]} | [{#{ letter => <<"h">>
 , min => 6
 , max => 11
 }, [<<"hhhhhhhhhhhhhhh">> | []]} | [{#{ letter => <<"v">>
 , min => 4
 , max => 7
 }, [<<"vvvsrqn">> | []]} | [{#{ letter => <<"j">>
 , min => 4
 , max => 6
 }, [<<"pgphwjwxj">> | []]} | [{#{ letter => <<"q">>
 , min => 14
 , max => 15
 }, [<<"qqqqqqqqlqqqqsq">> | []]} | [{#{ letter => <<"t">>
 , min => 9
 , max => 10
 }, [<<"ttttnpxtttttt">> | []]} | [{#{ letter => <<"m">>
 , min => 3
 , max => 4
 }, [<<"dwkj">> | []]} | [{#{ letter => <<"m">>
 , min => 7
 , max => 11
 }, [<<"mmtmcmmjdpggmm">> | []]} | [{#{ letter => <<"c">>
 , min => 1
 , max => 7
 }, [<<"crccnlrccccs">> | []]} | [{#{ letter => <<"m">>
 , min => 3
 , max => 7
 }, [<<"llczxdkcmpsbmpbmnmv">> | []]} | [{#{ letter => <<"k">>
 , min => 2
 , max => 4
 }, [<<"fckkfbkjd">> | []]} | [{#{ letter => <<"p">>
 , min => 15
 , max => 16
 }, [<<"hnhwphpktppppppp">> | []]} | [{#{ letter => <<"g">>
 , min => 12
 , max => 15
 }, [<<"ghggvzgqhkbgtgg">> | []]} | [{#{ letter => <<"q">>
 , min => 1
 , max => 3
 }, [<<"kqqqktqq">> | []]} | [{#{ letter => <<"g">>
 , min => 1
 , max => 8
 }, [<<"bzsjpsrshsggdm">> | []]} | [{#{ letter => <<"b">>
 , min => 1
 , max => 6
 }, [<<"bbbbbbbbb">> | []]} | [{#{ letter => <<"v">>
 , min => 17
 , max => 18
 }, [<<"hfvqvvvvvbvvfvvbgs">> | []]} | [{#{ letter => <<"z">>
 , min => 2
 , max => 11
 }, [<<"wzcxsgzkqfzx">> | []]} | [{#{ letter => <<"z">>
 , min => 8
 , max => 11
 }, [<<"fbxzgzlzzzzpzzvkzz">> | []]} | [{#{ letter => <<"g">>
 , min => 2
 , max => 15
 }, [<<"hghsqkjhjgldscgh">> | []]} | [{#{ letter => <<"p">>
 , min => 5
 , max => 7
 }, [<<"pvfppppp">> | []]} | [{#{ letter => <<"z">>
 , min => 4
 , max => 14
 }, [<<"zzzzvzmzkrzrzmpzzfz">> | []]} | [{#{ letter => <<"z">>
 , min => 1
 , max => 4
 }, [<<"zzfzzzljzzgznzzzzz">> | []]} | [{#{ letter => <<"c">>
 , min => 5
 , max => 6
 }, [<<"cccccc">> | []]} | [{#{ letter => <<"j">>
 , min => 5
 , max => 11
 }, [<<"jkmrhqksjpj">> | []]} | [{#{ letter => <<"f">>
 , min => 1
 , max => 3
 }, [<<"bffwff">> | []]} | [{#{ letter => <<"d">>
 , min => 4
 , max => 8
 }, [<<"dtddzddmd">> | []]} | [{#{ letter => <<"s">>
 , min => 14
 , max => 15
 }, [<<"sswsssssssssstqs">> | []]} | [{#{ letter => <<"j">>
 , min => 6
 , max => 18
 }, [<<"tjjzhmbsxgkwcdmjpj">> | []]} | [{#{ letter => <<"d">>
 , min => 2
 , max => 6
 }, [<<"qddddwqcdjldbsd">> | []]} | [{#{ letter => <<"t">>
 , min => 9
 , max => 11
 }, [<<"wqtjttwtctttttt">> | []]} | [{#{ letter => <<"q">>
 , min => 7
 , max => 8
 }, [<<"rqvhnctm">> | []]} | [{#{ letter => <<"k">>
 , min => 7
 , max => 10
 }, [<<"nqkdtkrkwvkkkbpk">> | []]} | [{#{ letter => <<"l">>
 , min => 5
 , max => 6
 }, [<<"lllllm">> | []]} | [{#{ letter => <<"p">>
 , min => 2
 , max => 4
 }, [<<"pkpp">> | []]} | [{#{ letter => <<"t">>
 , min => 3
 , max => 6
 }, [<<"psxjqth">> | []]} | [{#{ letter => <<"j">>
 , min => 1
 , max => 2
 }, [<<"xjwnjff">> | []]} | [{#{ letter => <<"t">>
 , min => 3
 , max => 4
 }, [<<"zqbt">> | []]} | [{#{ letter => <<"c">>
 , min => 3
 , max => 7
 }, [<<"qcccgwg">> | []]} | [{#{ letter => <<"q">>
 , min => 3
 , max => 5
 }, [<<"ncqqlt">> | []]} | [{#{ letter => <<"h">>
 , min => 1
 , max => 4
 }, [<<"fhhh">> | []]} | [{#{ letter => <<"x">>
 , min => 6
 , max => 8
 }, [<<"xxxxxxxxxx">> | []]} | [{#{ letter => <<"r">>
 , min => 1
 , max => 5
 }, [<<"rrnkrrpfrdfrxx">> | []]} | [{#{ letter => <<"b">>
 , min => 3
 , max => 6
 }, [<<"lcbbbqmhbbsb">> | []]} | [{#{ letter => <<"z">>
 , min => 6
 , max => 15
 }, [<<"qtfvzzskzsdqqxdkzsh">> | []]} | [{#{ letter => <<"d">>
 , min => 9
 , max => 11
 }, [<<"qpcdwddqxdzf">> | []]} | [{#{ letter => <<"k">>
 , min => 4
 , max => 5
 }, [<<"kkkkkwznkgtk">> | []]} | [{#{ letter => <<"h">>
 , min => 3
 , max => 4
 }, [<<"hhdgr">> | []]} | [{#{ letter => <<"p">>
 , min => 10
 , max => 12
 }, [<<"ppcppplppppz">> | []]} | [{#{ letter => <<"g">>
 , min => 3
 , max => 9
 }, [<<"xcgnnhstgtmqdpwghx">> | []]} | [{#{ letter => <<"g">>
 , min => 3
 , max => 4
 }, [<<"gggg">> | []]} | [{#{ letter => <<"k">>
 , min => 10
 , max => 12
 }, [<<"krkkwglqbrkkkkkkj">> | []]} | [{#{ letter => <<"d">>
 , min => 11
 , max => 14
 }, [<<"dddddddvdddddvw">> | []]} | [{#{ letter => <<"k">>
 , min => 4
 , max => 12
 }, [<<"khlkkksjkkkktkk">> | []]} | [{#{ letter => <<"p">>
 , min => 15
 , max => 17
 }, [<<"xsmppwpxxqpwtdjhj">> | []]} | [{#{ letter => <<"q">>
 , min => 6
 , max => 11
 }, [<<"dtxjgzcpxcmqhlnqr">> | []]} | [{#{ letter => <<"q">>
 , min => 9
 , max => 11
 }, [<<"qqqqqqqqjtr">> | []]} | [{#{ letter => <<"h">>
 , min => 10
 , max => 14
 }, [<<"hgphhzqkvhsjhhn">> | []]} | [{#{ letter => <<"v">>
 , min => 12
 , max => 16
 }, [<<"ghvvvmhvvvvvvsvbvv">> | []]} | [{#{ letter => <<"x">>
 , min => 1
 , max => 2
 }, [<<"xqxx">> | []]} | [{#{ letter => <<"r">>
 , min => 7
 , max => 9
 }, [<<"rbrrrrrjd">> | []]} | [{#{ letter => <<"z">>
 , min => 15
 , max => 16
 }, [<<"zzzzzzzzzzzczzmxz">> | []]} | [{#{ letter => <<"x">>
 , min => 11
 , max => 12
 }, [<<"xxjxkxkxxxrdbxxxkx">> | []]} | [{#{ letter => <<"b">>
 , min => 6
 , max => 7
 }, [<<"gbrbbwc">> | []]} | [{#{ letter => <<"q">>
 , min => 8
 , max => 9
 }, [<<"qqqqqqqdq">> | []]} | [{#{ letter => <<"x">>
 , min => 10
 , max => 16
 }, [<<"fxxxxxxxxxxxxxxrx">> | []]} | [{#{ letter => <<"f">>
 , min => 5
 , max => 8
 }, [<<"fffffhsdmgfb">> | []]} | [{#{ letter => <<"p">>
 , min => 6
 , max => 7
 }, [<<"kppcppt">> | []]} | [{#{ letter => <<"z">>
 , min => 8
 , max => 9
 }, [<<"zqzzzzzbczrz">> | []]} | [{#{ letter => <<"d">>
 , min => 13
 , max => 14
 }, [<<"ddhvvdzddddcdcddddd">> | []]} | [{#{ letter => <<"p">>
 , min => 5
 , max => 8
 }, [<<"ppppppph">> | []]} | [{#{ letter => <<"b">>
 , min => 8
 , max => 10
 }, [<<"bbbbbbbjbb">> | []]} | [{#{ letter => <<"j">>
 , min => 1
 , max => 6
 }, [<<"xjcwnnwwmgjcxfkpw">> | []]} | [{#{ letter => <<"v">>
 , min => 11
 , max => 18
 }, [<<"vvvvvvvvvvxvvvvvvvv">> | []]} | [{#{ letter => <<"j">>
 , min => 4
 , max => 5
 }, [<<"xjjls">> | []]} | [{#{ letter => <<"g">>
 , min => 1
 , max => 4
 }, [<<"ggggg">> | []]} | [{#{ letter => <<"m">>
 , min => 2
 , max => 4
 }, [<<"cmmm">> | []]} | [{#{ letter => <<"g">>
 , min => 1
 , max => 7
 }, [<<"gkggnwg">> | []]} | [{#{ letter => <<"t">>
 , min => 7
 , max => 10
 }, [<<"btwtgttrmwtptmt">> | []]} | [{#{ letter => <<"t">>
 , min => 6
 , max => 7
 }, [<<"vtzltkt">> | []]} | [{#{ letter => <<"n">>
 , min => 4
 , max => 7
 }, [<<"jcdnbwnn">> | []]} | [{#{ letter => <<"f">>
 , min => 8
 , max => 14
 }, [<<"fffvblcftkfqff">> | []]} | [{#{ letter => <<"c">>
 , min => 4
 , max => 10
 }, [<<"ccccccmccc">> | []]} | [{#{ letter => <<"l">>
 , min => 1
 , max => 6
 }, [<<"lllljgllll">> | []]} | [{#{ letter => <<"w">>
 , min => 1
 , max => 6
 }, [<<"hkwdfpkp">> | []]} | [{#{ letter => <<"n">>
 , min => 6
 , max => 10
 }, [<<"znnnctlnklnnnrn">> | []]} | [{#{ letter => <<"s">>
 , min => 3
 , max => 6
 }, [<<"fsshbttssbqb">> | []]} | [{#{ letter => <<"s">>
 , min => 11
 , max => 14
 }, [<<"sszsssslssmssq">> | []]} | [{#{ letter => <<"l">>
 , min => 1
 , max => 4
 }, [<<"jwll">> | []]} | [{#{ letter => <<"b">>
 , min => 1
 , max => 11
 }, [<<"bbblbbbbbbbb">> | []]} | [{#{ letter => <<"p">>
 , min => 11
 , max => 12
 }, [<<"ppppppppppdvppppppp">> | []]} | [{#{ letter => <<"q">>
 , min => 8
 , max => 11
 }, [<<"pqjqwqqwqqck">> | []]} | [{#{ letter => <<"r">>
 , min => 9
 , max => 11
 }, [<<"rrrrrrrrfrrrr">> | []]} | [{#{ letter => <<"p">>
 , min => 4
 , max => 8
 }, [<<"pppfpppb">> | []]} | [{#{ letter => <<"g">>
 , min => 15
 , max => 16
 }, [<<"ggggggggggggkggg">> | []]} | [{#{ letter => <<"m">>
 , min => 1
 , max => 11
 }, [<<"fzpmdrbhlbmmshk">> | []]} | [{#{ letter => <<"j">>
 , min => 3
 , max => 17
 }, [<<"pmpjvtlxhlpcwphpjjb">> | []]} | [{#{ letter => <<"s">>
 , min => 3
 , max => 4
 }, [<<"cjsz">> | []]} | [{#{ letter => <<"z">>
 , min => 10
 , max => 11
 }, [<<"zzzzzvzzzzzz">> | []]} | [{#{ letter => <<"p">>
 , min => 1
 , max => 2
 }, [<<"bvppp">> | []]} | [{#{ letter => <<"w">>
 , min => 5
 , max => 9
 }, [<<"wgjbwwwwl">> | []]} | [{#{ letter => <<"r">>
 , min => 19
 , max => 20
 }, [<<"rrrrrrrrrrrrrrrrrrdm">> | []]} | [{#{ letter => <<"q">>
 , min => 4
 , max => 6
 }, [<<"fqqjbqqq">> | []]} | [{#{ letter => <<"s">>
 , min => 2
 , max => 11
 }, [<<"wplxcnbdspsdlh">> | []]} | [{#{ letter => <<"d">>
 , min => 3
 , max => 13
 }, [<<"dlvmkddkgdrfgxhxldg">> | []]} | [{#{ letter => <<"d">>
 , min => 4
 , max => 8
 }, [<<"wsdrldsdwzdddjnfh">> | []]} | [{#{ letter => <<"j">>
 , min => 1
 , max => 10
 }, [<<"tjbwrzcnlcjjhkrsjjj">> | []]} | [{#{ letter => <<"m">>
 , min => 2
 , max => 3
 }, [<<"mmwm">> | []]} | [{#{ letter => <<"b">>
 , min => 7
 , max => 10
 }, [<<"lcbbbbcrfb">> | []]} | [{#{ letter => <<"c">>
 , min => 18
 , max => 19
 }, [<<"cgcccrccfccccccccnc">> | []]} | [{#{ letter => <<"j">>
 , min => 3
 , max => 5
 }, [<<"jjpjfjjjj">> | []]} | [{#{ letter => <<"c">>
 , min => 13
 , max => 14
 }, [<<"cckccccccccccccc">> | []]} | [{#{ letter => <<"q">>
 , min => 4
 , max => 9
 }, [<<"qqqqqqqqlqqq">> | []]} | [{#{ letter => <<"w">>
 , min => 3
 , max => 6
 }, [<<"twwvwwhmkwnjnss">> | []]} | [{#{ letter => <<"p">>
 , min => 8
 , max => 9
 }, [<<"pppzpppzcp">> | []]} | [{#{ letter => <<"l">>
 , min => 9
 , max => 10
 }, [<<"lllslvllwc">> | []]} | [{#{ letter => <<"m">>
 , min => 4
 , max => 7
 }, [<<"sjmhhhmr">> | []]} | [{#{ letter => <<"v">>
 , min => 1
 , max => 4
 }, [<<"vvrnvvtv">> | []]} | [{#{ letter => <<"r">>
 , min => 1
 , max => 4
 }, [<<"rmrrrcrrcprrrrbnq">> | []]} | [{#{ letter => <<"g">>
 , min => 7
 , max => 11
 }, [<<"ggghggggkgdwg">> | []]} | [{#{ letter => <<"l">>
 , min => 2
 , max => 12
 }, [<<"lmlllllllllllll">> | []]} | [{#{ letter => <<"q">>
 , min => 1
 , max => 3
 }, [<<"qqqq">> | []]} | [{#{ letter => <<"x">>
 , min => 11
 , max => 12
 }, [<<"xxxxxdxpmxxxx">> | []]} | [{#{ letter => <<"q">>
 , min => 2
 , max => 3
 }, [<<"qqqh">> | []]} | [{#{ letter => <<"w">>
 , min => 5
 , max => 6
 }, [<<"wwkwwwwgb">> | []]} | [{#{ letter => <<"w">>
 , min => 10
 , max => 11
 }, [<<"wwhwwwvwwwwww">> | []]} | [{#{ letter => <<"c">>
 , min => 1
 , max => 12
 }, [<<"vcccccccccccc">> | []]} | [{#{ letter => <<"r">>
 , min => 1
 , max => 3
 }, [<<"rrlrr">> | []]} | [{#{ letter => <<"w">>
 , min => 7
 , max => 12
 }, [<<"qpfcxwnvwzhwzvgwpwcm">> | []]} | [{#{ letter => <<"g">>
 , min => 7
 , max => 9
 }, [<<"ggggggfglg">> | []]} | [{#{ letter => <<"j">>
 , min => 2
 , max => 6
 }, [<<"cjqzkl">> | []]} | [{#{ letter => <<"w">>
 , min => 5
 , max => 7
 }, [<<"wwrwmwww">> | []]} | [{#{ letter => <<"q">>
 , min => 6
 , max => 12
 }, [<<"shqjlnqgkfcq">> | []]} | [{#{ letter => <<"d">>
 , min => 11
 , max => 12
 }, [<<"gddddddcddxd">> | []]} | [{#{ letter => <<"x">>
 , min => 3
 , max => 5
 }, [<<"xxxxh">> | []]} | [{#{ letter => <<"b">>
 , min => 6
 , max => 12
 }, [<<"bpmbmbbbbrdb">> | []]} | [{#{ letter => <<"j">>
 , min => 5
 , max => 7
 }, [<<"jtxbwtj">> | []]} | [{#{ letter => <<"t">>
 , min => 5
 , max => 6
 }, [<<"tntttv">> | []]} | [{#{ letter => <<"t">>
 , min => 17
 , max => 18
 }, [<<"tttttttttttttwttsms">> | []]} | [{#{ letter => <<"g">>
 , min => 7
 , max => 15
 }, [<<"gcghxlgzlgrdklnggtl">> | []]} | [{#{ letter => <<"s">>
 , min => 7
 , max => 12
 }, [<<"sdpssdwmssssgs">> | []]} | [{#{ letter => <<"k">>
 , min => 7
 , max => 15
 }, [<<"kkpmsskkpzhkbdkksk">> | []]} | [{#{ letter => <<"b">>
 , min => 5
 , max => 6
 }, [<<"bbbbbb">> | []]} | [{#{ letter => <<"c">>
 , min => 4
 , max => 7
 }, [<<"hxccchdrf">> | []]} | [{#{ letter => <<"z">>
 , min => 3
 , max => 6
 }, [<<"vzhzcpz">> | []]} | [{#{ letter => <<"q">>
 , min => 14
 , max => 16
 }, [<<"ppqrgfqvpmfjwqqz">> | []]} | [{#{ letter => <<"g">>
 , min => 5
 , max => 6
 }, [<<"svgwgxrnmngrgg">> | []]} | [{#{ letter => <<"p">>
 , min => 2
 , max => 13
 }, [<<"spkpvpdlcprlb">> | []]} | [{#{ letter => <<"v">>
 , min => 1
 , max => 4
 }, [<<"vvvv">> | []]} | [{#{ letter => <<"r">>
 , min => 10
 , max => 11
 }, [<<"xrjcrrrrwrrh">> | []]} | [{#{ letter => <<"h">>
 , min => 6
 , max => 11
 }, [<<"hhhvchbhhhphhhhh">> | []]} | [{#{ letter => <<"w">>
 , min => 7
 , max => 9
 }, [<<"wjwwwwzzwwkwbkrl">> | []]} | [{#{ letter => <<"x">>
 , min => 7
 , max => 11
 }, [<<"xxdxcllxxxr">> | []]} | [{#{ letter => <<"b">>
 , min => 6
 , max => 17
 }, [<<"brthfqjmbbbbbfljbfb">> | []]} | [{#{ letter => <<"l">>
 , min => 11
 , max => 12
 }, [<<"lclllzllllxjdl">> | []]} | [{#{ letter => <<"g">>
 , min => 7
 , max => 12
 }, [<<"gchglbgmggbqvg">> | []]} | [{#{ letter => <<"z">>
 , min => 2
 , max => 5
 }, [<<"zzpjzqzz">> | []]} | [{#{ letter => <<"h">>
 , min => 7
 , max => 16
 }, [<<"hhhqndzhnhpzhqhhmhb">> | []]} | [{#{ letter => <<"k">>
 , min => 16
 , max => 17
 }, [<<"kkkkzkkkkkkwfkkckkkk">> | []]} | [{#{ letter => <<"v">>
 , min => 2
 , max => 3
 }, [<<"vgbvv">> | []]} | [{#{ letter => <<"j">>
 , min => 9
 , max => 10
 }, [<<"jjjjjjjjjv">> | []]} | [{#{ letter => <<"n">>
 , min => 1
 , max => 4
 }, [<<"cnxn">> | []]} | [{#{ letter => <<"s">>
 , min => 7
 , max => 10
 }, [<<"sssssssssssstsbss">> | []]} | [{#{ letter => <<"s">>
 , min => 3
 , max => 12
 }, [<<"ksjbxfhcsswstr">> | []]} | [{#{ letter => <<"z">>
 , min => 4
 , max => 15
 }, [<<"zpzmzzpzzzzzzzmzz">> | []]} | [{#{ letter => <<"q">>
 , min => 9
 , max => 12
 }, [<<"qpqwgcrqpqdp">> | []]} | [{#{ letter => <<"b">>
 , min => 2
 , max => 11
 }, [<<"bbhnnbdblgbbbbbgb">> | []]} | [{#{ letter => <<"h">>
 , min => 5
 , max => 6
 }, [<<"hhhhhhhhhhh">> | []]} | [{#{ letter => <<"t">>
 , min => 8
 , max => 12
 }, [<<"ttttttbttttttt">> | []]} | [{#{ letter => <<"t">>
 , min => 17
 , max => 18
 }, [<<"qtkstpsdthtvtftgthqw">> | []]} | [{#{ letter => <<"l">>
 , min => 2
 , max => 6
 }, [<<"lplllll">> | []]} | [{#{ letter => <<"c">>
 , min => 6
 , max => 7
 }, [<<"zmqjcbmrcclzcc">> | []]} | [{#{ letter => <<"z">>
 , min => 5
 , max => 16
 }, [<<"zzzzdzzzzzzzjzztm">> | []]} | [{#{ letter => <<"b">>
 , min => 10
 , max => 14
 }, [<<"qrjbbbbblkrbbwbbrcbc">> | []]} | [{#{ letter => <<"d">>
 , min => 2
 , max => 15
 }, [<<"dgdddddddwddddzdd">> | []]} | [{#{ letter => <<"p">>
 , min => 3
 , max => 8
 }, [<<"zmmhfppjlrwnpp">> | []]} | [{#{ letter => <<"r">>
 , min => 17
 , max => 19
 }, [<<"krrhprxrrrnfqkslrpr">> | []]} | [{#{ letter => <<"n">>
 , min => 7
 , max => 10
 }, [<<"nnnnnnnnsqn">> | []]} | [{#{ letter => <<"g">>
 , min => 3
 , max => 10
 }, [<<"gggggzggghjgggwggg">> | []]} | [{#{ letter => <<"x">>
 , min => 1
 , max => 4
 }, [<<"sxxxxf">> | []]} | [{#{ letter => <<"j">>
 , min => 6
 , max => 11
 }, [<<"jjljjtjjjjj">> | []]} | [{#{ letter => <<"f">>
 , min => 7
 , max => 8
 }, [<<"fffffffff">> | []]} | [{#{ letter => <<"n">>
 , min => 2
 , max => 3
 }, [<<"knndzlnhz">> | []]} | [{#{ letter => <<"l">>
 , min => 4
 , max => 7
 }, [<<"lgplzpkjq">> | []]} | [{#{ letter => <<"z">>
 , min => 9
 , max => 10
 }, [<<"zzzzzzzbszzr">> | []]} | [{#{ letter => <<"h">>
 , min => 8
 , max => 13
 }, [<<"kdhhhhhhhkrgchhh">> | []]} | [{#{ letter => <<"d">>
 , min => 1
 , max => 3
 }, [<<"lddrbd">> | []]} | [{#{ letter => <<"n">>
 , min => 18
 , max => 19
 }, [<<"nnnnnnnnnxnnnnnnnns">> | []]} | [{#{ letter => <<"x">>
 , min => 4
 , max => 7
 }, [<<"gxxqxxxxjcxl">> | []]} | [{#{ letter => <<"r">>
 , min => 5
 , max => 13
 }, [<<"trfthwjntjlwn">> | []]} | [{#{ letter => <<"d">>
 , min => 8
 , max => 12
 }, [<<"xxpdjrdwbddddmdqvd">> | []]} | [{#{ letter => <<"j">>
 , min => 5
 , max => 6
 }, [<<"jxjjvkd">> | []]} | [{#{ letter => <<"b">>
 , min => 4
 , max => 5
 }, [<<"dmwpbbx">> | []]} | [{#{ letter => <<"w">>
 , min => 3
 , max => 4
 }, [<<"wjwl">> | []]} | [{#{ letter => <<"s">>
 , min => 2
 , max => 3
 }, [<<"ssjss">> | []]} | [{#{ letter => <<"m">>
 , min => 1
 , max => 6
 }, [<<"mhkmsthqxrxmqq">> | []]} | [{#{ letter => <<"c">>
 , min => 7
 , max => 16
 }, [<<"vzqnsscchrkjpckwn">> | []]} | [{#{ letter => <<"p">>
 , min => 10
 , max => 15
 }, [<<"ppfzpdppppzpphsvpppq">> | []]} | [{#{ letter => <<"g">>
 , min => 3
 , max => 19
 }, [<<"lgxbrcsvgzrncgzggdgg">> | []]} | [{#{ letter => <<"h">>
 , min => 10
 , max => 14
 }, [<<"phtzhhhhhhhhkjn">> | []]} | [{#{ letter => <<"f">>
 , min => 15
 , max => 16
 }, [<<"ffffffffffffffdff">> | []]} | [{#{ letter => <<"x">>
 , min => 1
 , max => 4
 }, [<<"xmlxjlblpctjxzmdgkgr">> | []]} | [{#{ letter => <<"c">>
 , min => 10
 , max => 12
 }, [<<"cpcccccccwcdcccccccv">> | []]} | [{#{ letter => <<"t">>
 , min => 3
 , max => 4
 }, [<<"tstt">> | []]} | [{#{ letter => <<"s">>
 , min => 10
 , max => 14
 }, [<<"ssldsssssrshsvs">> | []]} | [{#{ letter => <<"v">>
 , min => 7
 , max => 9
 }, [<<"vvvvvvvvv">> | []]} | [{#{ letter => <<"c">>
 , min => 11
 , max => 13
 }, [<<"cccfcccctccksczcct">> | []]} | [{#{ letter => <<"c">>
 , min => 5
 , max => 6
 }, [<<"zcccrl">> | []]} | [{#{ letter => <<"p">>
 , min => 12
 , max => 18
 }, [<<"ppgppdlgqpkpwppkphp">> | []]} | [{#{ letter => <<"v">>
 , min => 10
 , max => 16
 }, [<<"vvvvvvvvvvvvmvvhvv">> | []]} | [{#{ letter => <<"n">>
 , min => 15
 , max => 16
 }, [<<"nnnnnnnnnnnnnntnnn">> | []]} | [{#{ letter => <<"t">>
 , min => 15
 , max => 18
 }, [<<"tzktddqnhtjtsktlkt">> | []]} | [{#{ letter => <<"q">>
 , min => 4
 , max => 7
 }, [<<"mqjbqkqlqnqqdxn">> | []]} | [{#{ letter => <<"x">>
 , min => 1
 , max => 3
 }, [<<"fxcx">> | []]} | [{#{ letter => <<"c">>
 , min => 5
 , max => 6
 }, [<<"jwccccxggtgcc">> | []]} | [{#{ letter => <<"m">>
 , min => 8
 , max => 16
 }, [<<"mpjmmpmmmmmcmmmc">> | []]} | [{#{ letter => <<"q">>
 , min => 7
 , max => 9
 }, [<<"qrwpkjfqzq">> | []]} | [{#{ letter => <<"g">>
 , min => 1
 , max => 12
 }, [<<"bsqgxbjngmgw">> | []]} | [{#{ letter => <<"w">>
 , min => 4
 , max => 5
 }, [<<"wwwbw">> | []]} | [{#{ letter => <<"r">>
 , min => 14
 , max => 17
 }, [<<"nvmrhtqdkqkbcrzjp">> | []]} | [{#{ letter => <<"b">>
 , min => 12
 , max => 14
 }, [<<"bbbbmbbbbvbrpr">> | []]} | [{#{ letter => <<"s">>
 , min => 7
 , max => 8
 }, [<<"ksssssls">> | []]} | [{#{ letter => <<"m">>
 , min => 10
 , max => 12
 }, [<<"mmmjmwcfmbmmmmmm">> | []]} | [{#{ letter => <<"q">>
 , min => 3
 , max => 4
 }, [<<"cqqq">> | []]} | [{#{ letter => <<"d">>
 , min => 7
 , max => 9
 }, [<<"dvhqpbrjz">> | []]} | [{#{ letter => <<"b">>
 , min => 4
 , max => 5
 }, [<<"bhbxbzbm">> | []]} | [{#{ letter => <<"l">>
 , min => 10
 , max => 12
 }, [<<"llglllplhcgmtxlln">> | []]} | [{#{ letter => <<"j">>
 , min => 7
 , max => 12
 }, [<<"rpwrjzjxktwjjjr">> | []]} | [{#{ letter => <<"m">>
 , min => 12
 , max => 14
 }, [<<"cdmdcmkzknfmgwvwxfm">> | []]} | [{#{ letter => <<"b">>
 , min => 1
 , max => 2
 }, [<<"bbnt">> | []]} | [{#{ letter => <<"h">>
 , min => 4
 , max => 16
 }, [<<"hlhhdhhzhhmlzqhhh">> | []]} | [{#{ letter => <<"d">>
 , min => 2
 , max => 5
 }, [<<"dqfwxgccx">> | []]} | [{#{ letter => <<"q">>
 , min => 4
 , max => 8
 }, [<<"vnqtwhsqvsnqw">> | []]} | [{#{ letter => <<"k">>
 , min => 7
 , max => 8
 }, [<<"kxhkpssk">> | []]} | [{#{ letter => <<"t">>
 , min => 8
 , max => 13
 }, [<<"zbmtwrbcvhfhj">> | []]} | [{#{ letter => <<"s">>
 , min => 5
 , max => 8
 }, [<<"hshrssvclnjs">> | []]} | [{#{ letter => <<"v">>
 , min => 10
 , max => 12
 }, [<<"rfwhbpxrtwpvvt">> | []]} | [{#{ letter => <<"l">>
 , min => 3
 , max => 6
 }, [<<"lllstl">> | []]} | [{#{ letter => <<"d">>
 , min => 5
 , max => 6
 }, [<<"dfhbxq">> | []]} | [{#{ letter => <<"d">>
 , min => 7
 , max => 12
 }, [<<"dwldsrddmnddv">> | []]} | [{#{ letter => <<"v">>
 , min => 7
 , max => 8
 }, [<<"vvljwkvh">> | []]} | [{#{ letter => <<"b">>
 , min => 3
 , max => 4
 }, [<<"wdkhbbrxmcr">> | []]} | [{#{ letter => <<"v">>
 , min => 3
 , max => 5
 }, [<<"cvvvvvvhr">> | []]} | [{#{ letter => <<"h">>
 , min => 5
 , max => 7
 }, [<<"hjhhqhzhhw">> | []]} | [{#{ letter => <<"n">>
 , min => 3
 , max => 5
 }, [<<"nlndkn">> | []]} | [{#{ letter => <<"t">>
 , min => 6
 , max => 8
 }, [<<"zttttjtml">> | []]} | [{#{ letter => <<"r">>
 , min => 1
 , max => 7
 }, [<<"trrrrrrrrr">> | []]} | [{#{ letter => <<"h">>
 , min => 3
 , max => 6
 }, [<<"nzgxhzhftnhchhvt">> | []]} | [{#{ letter => <<"s">>
 , min => 8
 , max => 9
 }, [<<"ksssssfsrss">> | []]} | [{#{ letter => <<"l">>
 , min => 1
 , max => 6
 }, [<<"lqxqgw">> | []]} | [{#{ letter => <<"v">>
 , min => 18
 , max => 20
 }, [<<"vvvvgvvvvvvvvvvvvlvq">> | []]} | [{#{ letter => <<"q">>
 , min => 2
 , max => 4
 }, [<<"bqlqhxqxrxqqzq">> | []]} | [{#{ letter => <<"s">>
 , min => 3
 , max => 18
 }, [<<"fdcswgtgxlhfvzzznssh">> | []]} | [{#{ letter => <<"p">>
 , min => 9
 , max => 10
 }, [<<"ppzsplppppvhppd">> | []]} | [{#{ letter => <<"b">>
 , min => 12
 , max => 13
 }, [<<"bbbbbbbbbbbbbb">> | []]} | [{#{ letter => <<"w">>
 , min => 12
 , max => 16
 }, [<<"wwwwwwtwwwwwwwwrwww">> | []]} | [{#{ letter => <<"h">>
 , min => 6
 , max => 8
 }, [<<"hhmhhxhbf">> | []]} | [{#{ letter => <<"c">>
 , min => 1
 , max => 7
 }, [<<"gpdvnmnbgtlnwlzx">> | []]} | [{#{ letter => <<"z">>
 , min => 3
 , max => 4
 }, [<<"zzzz">> | []]} | [{#{ letter => <<"m">>
 , min => 4
 , max => 9
 }, [<<"gzmmdcdgm">> | []]} | [{#{ letter => <<"t">>
 , min => 2
 , max => 4
 }, [<<"vgsttn">> | []]} | [{#{ letter => <<"r">>
 , min => 1
 , max => 8
 }, [<<"rrlrrrlr">> | []]} | [{#{ letter => <<"w">>
 , min => 5
 , max => 10
 }, [<<"rrwgwfrprpvww">> | []]} | [{#{ letter => <<"r">>
 , min => 1
 , max => 4
 }, [<<"srrr">> | []]} | [{#{ letter => <<"r">>
 , min => 11
 , max => 12
 }, [<<"rrrrrrrrrrbrrrrrr">> | []]} | [{#{ letter => <<"c">>
 , min => 3
 , max => 5
 }, [<<"gqvcnctdwn">> | []]} | [{#{ letter => <<"p">>
 , min => 4
 , max => 6
 }, [<<"mrmvppprp">> | []]} | [{#{ letter => <<"l">>
 , min => 2
 , max => 3
 }, [<<"kxlvdtgtlhsrl">> | []]} | [{#{ letter => <<"h">>
 , min => 8
 , max => 16
 }, [<<"chchhhhzfhshhhhhh">> | []]} | [{#{ letter => <<"r">>
 , min => 6
 , max => 8
 }, [<<"rrrrrfrrr">> | []]} | [{#{ letter => <<"t">>
 , min => 17
 , max => 20
 }, [<<"ptttttttnttttktttttt">> | []]} | [{#{ letter => <<"r">>
 , min => 6
 , max => 9
 }, [<<"zbltfrdlrwrj">> | []]} | [{#{ letter => <<"d">>
 , min => 6
 , max => 7
 }, [<<"gqhsddd">> | []]} | [{#{ letter => <<"j">>
 , min => 3
 , max => 5
 }, [<<"mtlhj">> | []]} | [{#{ letter => <<"x">>
 , min => 17
 , max => 18
 }, [<<"xpxxxxxxxxxxxxxxnxxt">> | []]} | [{#{ letter => <<"n">>
 , min => 7
 , max => 11
 }, [<<"vpnnnncnnbnn">> | []]} | [{#{ letter => <<"q">>
 , min => 3
 , max => 4
 }, [<<"cqlhqqqsvfz">> | []]} | [{#{ letter => <<"f">>
 , min => 8
 , max => 12
 }, [<<"ffffffffffff">> | []]} | [{#{ letter => <<"g">>
 , min => 3
 , max => 4
 }, [<<"fbksgtqggggggrgg">> | []]} | [{#{ letter => <<"d">>
 , min => 7
 , max => 9
 }, [<<"skntdmdcdzmnhvdj">> | []]} | [{#{ letter => <<"w">>
 , min => 7
 , max => 10
 }, [<<"wwwwwwbwww">> | []]} | [{#{ letter => <<"r">>
 , min => 10
 , max => 11
 }, [<<"fgpkwrwqgbs">> | []]} | [{#{ letter => <<"h">>
 , min => 9
 , max => 10
 }, [<<"hhhjchhhnhh">> | []]} | [{#{ letter => <<"d">>
 , min => 11
 , max => 12
 }, [<<"ddddddddddkh">> | []]} | [{#{ letter => <<"c">>
 , min => 9
 , max => 11
 }, [<<"czzjtllcdff">> | []]} | [{#{ letter => <<"t">>
 , min => 1
 , max => 2
 }, [<<"rrxdnzf">> | []]} | [{#{ letter => <<"n">>
 , min => 3
 , max => 4
 }, [<<"nndk">> | []]} | [{#{ letter => <<"m">>
 , min => 1
 , max => 2
 }, [<<"qqvmh">> | []]} | [{#{ letter => <<"x">>
 , min => 7
 , max => 9
 }, [<<"qbxkxxxxxxx">> | []]} | [{#{ letter => <<"v">>
 , min => 3
 , max => 13
 }, [<<"vgvtfmtwnrfbxvtkt">> | []]} | [{#{ letter => <<"j">>
 , min => 2
 , max => 5
 }, [<<"tjpjjrlxzjjcsl">> | []]} | [{#{ letter => <<"z">>
 , min => 13
 , max => 14
 }, [<<"zzzzzzzzzzzzbz">> | []]} | [{#{ letter => <<"w">>
 , min => 2
 , max => 4
 }, [<<"wwww">> | []]} | [{#{ letter => <<"x">>
 , min => 5
 , max => 6
 }, [<<"xxxxxdx">> | []]} | [{#{ letter => <<"p">>
 , min => 2
 , max => 12
 }, [<<"pppppfpvfppcmpd">> | []]} | [{#{ letter => <<"r">>
 , min => 4
 , max => 5
 }, [<<"rrrwfrr">> | []]} | [{#{ letter => <<"c">>
 , min => 3
 , max => 8
 }, [<<"cwmnsxcccjd">> | []]} | [{#{ letter => <<"j">>
 , min => 2
 , max => 4
 }, [<<"jjhh">> | []]} | [{#{ letter => <<"j">>
 , min => 4
 , max => 6
 }, [<<"ljtjvzqzktz">> | []]} | [{#{ letter => <<"v">>
 , min => 7
 , max => 9
 }, [<<"vvvvvvcfv">> | []]} | [{#{ letter => <<"m">>
 , min => 4
 , max => 6
 }, [<<"mmrmxmkmmmgr">> | []]} | [{#{ letter => <<"p">>
 , min => 6
 , max => 10
 }, [<<"cpkppbppppqplxr">> | []]} | [{#{ letter => <<"b">>
 , min => 12
 , max => 20
 }, [<<"stbmpspzhplbhhtbpbwb">> | []]} | [{#{ letter => <<"w">>
 , min => 5
 , max => 7
 }, [<<"wkwwbwhwwrwwswwwz">> | []]} | [{#{ letter => <<"r">>
 , min => 2
 , max => 7
 }, [<<"rssttxm">> | []]} | [{#{ letter => <<"r">>
 , min => 3
 , max => 8
 }, [<<"gcrtpkrrdrk">> | []]} | [{#{ letter => <<"d">>
 , min => 7
 , max => 9
 }, [<<"ddddddbdgsd">> | []]} | [{#{ letter => <<"w">>
 , min => 8
 , max => 10
 }, [<<"wwwwwwwwwwwww">> | []]} | [{#{ letter => <<"g">>
 , min => 11
 , max => 15
 }, [<<"ggdtgggrgggghggg">> | []]} | [{#{ letter => <<"j">>
 , min => 7
 , max => 14
 }, [<<"nfvlqhccbnwkjhwnnvt">> | []]} | [{#{ letter => <<"g">>
 , min => 14
 , max => 15
 }, [<<"gggggggggggggfg">> | []]} | [{#{ letter => <<"h">>
 , min => 14
 , max => 15
 }, [<<"hhhhhhhhhhhhhhv">> | []]} | [{#{ letter => <<"c">>
 , min => 5
 , max => 6
 }, [<<"pmccjccccrcc">> | []]} | [{#{ letter => <<"n">>
 , min => 2
 , max => 7
 }, [<<"vzxncpcdqzvqgmf">> | []]} | [{#{ letter => <<"z">>
 , min => 1
 , max => 4
 }, [<<"xzzz">> | []]} | [{#{ letter => <<"d">>
 , min => 7
 , max => 10
 }, [<<"ddddddnddd">> | []]} | [{#{ letter => <<"q">>
 , min => 5
 , max => 6
 }, [<<"qqqqqbq">> | []]} | [{#{ letter => <<"v">>
 , min => 4
 , max => 18
 }, [<<"vvvjvwvvcvrvnvwhvv">> | []]} | [{#{ letter => <<"x">>
 , min => 5
 , max => 6
 }, [<<"xxxxxb">> | []]} | [{#{ letter => <<"n">>
 , min => 3
 , max => 8
 }, [<<"jnnnnnnnz">> | []]} | [{#{ letter => <<"g">>
 , min => 4
 , max => 5
 }, [<<"ggngg">> | []]} | [{#{ letter => <<"f">>
 , min => 9
 , max => 11
 }, [<<"bsffzfvfffxffjtf">> | []]} | [{#{ letter => <<"p">>
 , min => 7
 , max => 9
 }, [<<"pzpppppppprp">> | []]} | [{#{ letter => <<"x">>
 , min => 1
 , max => 4
 }, [<<"sxcxfx">> | []]} | [{#{ letter => <<"h">>
 , min => 4
 , max => 12
 }, [<<"hhtphhhhdhkghhchhvqh">> | []]} | [{#{ letter => <<"s">>
 , min => 9
 , max => 10
 }, [<<"ssssslsssss">> | []]} | [{#{ letter => <<"t">>
 , min => 1
 , max => 5
 }, [<<"ttttw">> | []]} | [{#{ letter => <<"b">>
 , min => 4
 , max => 7
 }, [<<"xbxxvxbdpnflzbzz">> | []]} | [{#{ letter => <<"f">>
 , min => 11
 , max => 12
 }, [<<"ndppjfvgbvndzgflkwj">> | []]} | [{#{ letter => <<"v">>
 , min => 4
 , max => 5
 }, [<<"vdlvk">> | []]} | [{#{ letter => <<"q">>
 , min => 6
 , max => 7
 }, [<<"qqvqbqqqql">> | []]} | [{#{ letter => <<"r">>
 , min => 3
 , max => 7
 }, [<<"rrjrrrr">> | []]} | [{#{ letter => <<"h">>
 , min => 7
 , max => 10
 }, [<<"dhhhqhbcbhhlhhhhf">> | []]} | [{#{ letter => <<"c">>
 , min => 12
 , max => 14
 }, [<<"cgccccccccccczcjc">> | []]} | [{#{ letter => <<"f">>
 , min => 1
 , max => 2
 }, [<<"fsff">> | []]} | [{#{ letter => <<"b">>
 , min => 7
 , max => 8
 }, [<<"cqqbcwxzbb">> | []]} | [{#{ letter => <<"j">>
 , min => 8
 , max => 13
 }, [<<"jjsgdjjnjxcjzjj">> | []]} | [{#{ letter => <<"h">>
 , min => 5
 , max => 7
 }, [<<"hhchhph">> | []]} | [{#{ letter => <<"g">>
 , min => 3
 , max => 6
 }, [<<"ggggglg">> | []]} | [{#{ letter => <<"g">>
 , min => 6
 , max => 9
 }, [<<"zgmsgggglwgngn">> | []]} | [{#{ letter => <<"s">>
 , min => 1
 , max => 6
 }, [<<"kmsssssspssss">> | []]} | [{#{ letter => <<"q">>
 , min => 1
 , max => 5
 }, [<<"fscrqmqqpqqqdtgspmc">> | []]} | [{#{ letter => <<"f">>
 , min => 5
 , max => 8
 }, [<<"cftsfmwff">> | []]} | [{#{ letter => <<"g">>
 , min => 2
 , max => 15
 }, [<<"cgvtzfjsxfgdsggtk">> | []]} | [{#{ letter => <<"v">>
 , min => 3
 , max => 4
 }, [<<"vhdq">> | []]} | [{#{ letter => <<"c">>
 , min => 13
 , max => 14
 }, [<<"ccccccccccccns">> | []]} | [{#{ letter => <<"z">>
 , min => 2
 , max => 4
 }, [<<"zzzz">> | []]} | [{#{ letter => <<"c">>
 , min => 2
 , max => 3
 }, [<<"ccscc">> | []]} | [{#{ letter => <<"x">>
 , min => 2
 , max => 12
 }, [<<"bxxxqxrbxlxlbxxvxxv">> | []]} | [{#{ letter => <<"f">>
 , min => 5
 , max => 9
 }, [<<"ffffsfmffxfff">> | []]} | [{#{ letter => <<"m">>
 , min => 10
 , max => 12
 }, [<<"wnmmjmmmmmmlmwk">> | []]} | [{#{ letter => <<"t">>
 , min => 1
 , max => 4
 }, [<<"ltttttt">> | []]} | [{#{ letter => <<"r">>
 , min => 2
 , max => 10
 }, [<<"brlrmrrrrljrvr">> | []]} | [{#{ letter => <<"p">>
 , min => 9
 , max => 13
 }, [<<"ppppmtppnpptps">> | []]} | [{#{ letter => <<"p">>
 , min => 3
 , max => 7
 }, [<<"pjppppppppbpw">> | []]} | [{#{ letter => <<"f">>
 , min => 7
 , max => 11
 }, [<<"fzfzzvfvfcfkffffffk">> | []]} | [{#{ letter => <<"p">>
 , min => 4
 , max => 6
 }, [<<"pppppp">> | []]} | [{#{ letter => <<"b">>
 , min => 5
 , max => 6
 }, [<<"blbbbb">> | []]} | [{#{ letter => <<"w">>
 , min => 9
 , max => 13
 }, [<<"wwzwwbwcnwtzw">> | []]} | [{#{ letter => <<"d">>
 , min => 4
 , max => 8
 }, [<<"jkjrdxnv">> | []]} | [{#{ letter => <<"t">>
 , min => 5
 , max => 7
 }, [<<"ttkttrsttppmttgtqtf">> | []]} | [{#{ letter => <<"n">>
 , min => 3
 , max => 4
 }, [<<"ngmn">> | []]} | [{#{ letter => <<"h">>
 , min => 5
 , max => 7
 }, [<<"cvhdhvbhnknhh">> | []]} | [{#{ letter => <<"m">>
 , min => 12
 , max => 13
 }, [<<"vsqmvcvgmmhmk">> | []]} | [{#{ letter => <<"s">>
 , min => 9
 , max => 10
 }, [<<"ssssssssts">> | []]} | [{#{ letter => <<"p">>
 , min => 5
 , max => 14
 }, [<<"pppkdppppbppppppppp">> | []]} | [{#{ letter => <<"v">>
 , min => 2
 , max => 4
 }, [<<"lbbcvhxgns">> | []]} | [{#{ letter => <<"g">>
 , min => 1
 , max => 4
 }, [<<"zggg">> | []]} | [{#{ letter => <<"f">>
 , min => 2
 , max => 3
 }, [<<"wgnf">> | []]} | [{#{ letter => <<"j">>
 , min => 6
 , max => 7
 }, [<<"jwcjjfjjjjxzjbjk">> | []]} | [{#{ letter => <<"b">>
 , min => 3
 , max => 15
 }, [<<"tvlrztbfwfbwqknhzbw">> | []]} | [{#{ letter => <<"g">>
 , min => 10
 , max => 11
 }, [<<"ggggggggfxk">> | []]} | [{#{ letter => <<"q">>
 , min => 2
 , max => 3
 }, [<<"vqqq">> | []]} | [{#{ letter => <<"v">>
 , min => 10
 , max => 13
 }, [<<"fcvvrvsvdvjvwvvxvgt">> | []]} | [{#{ letter => <<"c">>
 , min => 3
 , max => 4
 }, [<<"mcmc">> | []]} | [{#{ letter => <<"d">>
 , min => 3
 , max => 9
 }, [<<"xddqhsthcdpfsdd">> | []]} | [{#{ letter => <<"n">>
 , min => 11
 , max => 12
 }, [<<"mnnnlnncnkng">> | []]} | [{#{ letter => <<"p">>
 , min => 2
 , max => 10
 }, [<<"pppgpgppxmp">> | []]} | [{#{ letter => <<"s">>
 , min => 1
 , max => 4
 }, [<<"hswssss">> | []]} | [{#{ letter => <<"h">>
 , min => 3
 , max => 4
 }, [<<"zhhh">> | []]} | [{#{ letter => <<"f">>
 , min => 4
 , max => 8
 }, [<<"jnwfmtfjf">> | []]} | [{#{ letter => <<"z">>
 , min => 18
 , max => 19
 }, [<<"zzzzzzzzzzzzzzzzzzz">> | []]} | [{#{ letter => <<"h">>
 , min => 13
 , max => 16
 }, [<<"rghbhvnfsnvvhjjhd">> | []]} | [{#{ letter => <<"d">>
 , min => 7
 , max => 11
 }, [<<"cdddrddncffsdlddl">> | []]} | [{#{ letter => <<"w">>
 , min => 4
 , max => 5
 }, [<<"dgwnw">> | []]} | [{#{ letter => <<"v">>
 , min => 15
 , max => 17
 }, [<<"vvvvkvvvvfvqvvqvnnvv">> | []]} | [{#{ letter => <<"v">>
 , min => 6
 , max => 11
 }, [<<"gvvvvvvvvvv">> | []]} | [{#{ letter => <<"n">>
 , min => 18
 , max => 19
 }, [<<"nnnnnnnnnnnnnnnnnnn">> | []]} | [{#{ letter => <<"k">>
 , min => 4
 , max => 6
 }, [<<"tkkkzklkvbkk">> | []]} | [{#{ letter => <<"n">>
 , min => 12
 , max => 16
 }, [<<"nnnnnnnnnnnwnnnhnnn">> | []]} | [{#{ letter => <<"w">>
 , min => 2
 , max => 3
 }, [<<"wwww">> | []]} | [{#{ letter => <<"t">>
 , min => 13
 , max => 14
 }, [<<"tttttttttttttb">> | []]} | [{#{ letter => <<"j">>
 , min => 6
 , max => 9
 }, [<<"zjjjjfjjmjjj">> | []]} | [{#{ letter => <<"j">>
 , min => 3
 , max => 9
 }, [<<"ltljpknxj">> | []]} | [{#{ letter => <<"m">>
 , min => 4
 , max => 10
 }, [<<"wzmrmsvfwrjds">> | []]} | [{#{ letter => <<"s">>
 , min => 6
 , max => 9
 }, [<<"ssssszssw">> | []]} | [{#{ letter => <<"v">>
 , min => 4
 , max => 5
 }, [<<"vdnvvbbzvdns">> | []]} | [{#{ letter => <<"d">>
 , min => 4
 , max => 20
 }, [<<"ddvdvrpddwdddddtdsdd">> | []]} | [{#{ letter => <<"h">>
 , min => 1
 , max => 2
 }, [<<"jhvhh">> | []]} | [{#{ letter => <<"n">>
 , min => 2
 , max => 3
 }, [<<"ncnt">> | []]} | [{#{ letter => <<"f">>
 , min => 4
 , max => 6
 }, [<<"ffwfpff">> | []]} | [{#{ letter => <<"w">>
 , min => 3
 , max => 4
 }, [<<"gtwzxkw">> | []]} | [{#{ letter => <<"x">>
 , min => 8
 , max => 14
 }, [<<"twxqvxxgcpnxxxcwxx">> | []]} | [{#{ letter => <<"v">>
 , min => 1
 , max => 13
 }, [<<"tvvvvvvcvvvvvplvvvtv">> | []]} | [{#{ letter => <<"c">>
 , min => 7
 , max => 14
 }, [<<"rmrzctbccfcnrcdsdc">> | []]} | [{#{ letter => <<"b">>
 , min => 4
 , max => 8
 }, [<<"bbbbbbbjb">> | []]} | [{#{ letter => <<"t">>
 , min => 5
 , max => 15
 }, [<<"vzttttbtdttfqstt">> | []]} | [{#{ letter => <<"f">>
 , min => 9
 , max => 17
 }, [<<"fffpfffbfffxtfdfpf">> | []]} | [{#{ letter => <<"n">>
 , min => 7
 , max => 12
 }, [<<"nnnlnrccnnnld">> | []]} | [{#{ letter => <<"g">>
 , min => 3
 , max => 5
 }, [<<"ggpgrg">> | []]} | [{#{ letter => <<"w">>
 , min => 4
 , max => 5
 }, [<<"wknhd">> | []]} | [{#{ letter => <<"f">>
 , min => 9
 , max => 10
 }, [<<"wfbfrfffqkfkfg">> | []]} | [{#{ letter => <<"g">>
 , min => 3
 , max => 4
 }, [<<"ggtg">> | []]} | [{#{ letter => <<"c">>
 , min => 2
 , max => 5
 }, [<<"cqzdfcccpcc">> | []]} | [{#{ letter => <<"z">>
 , min => 2
 , max => 11
 }, [<<"gzhzxhdttbz">> | []]} | [{#{ letter => <<"j">>
 , min => 5
 , max => 7
 }, [<<"pxjjzwjskjjtj">> | []]} | [{#{ letter => <<"t">>
 , min => 4
 , max => 5
 }, [<<"ttttts">> | []]} | [{#{ letter => <<"c">>
 , min => 8
 , max => 9
 }, [<<"cqccjccqcc">> | []]} | [{#{ letter => <<"z">>
 , min => 6
 , max => 7
 }, [<<"zzzvzmvzl">> | []]} | [{#{ letter => <<"d">>
 , min => 9
 , max => 12
 }, [<<"ddddddddjdddd">> | []]} | [{#{ letter => <<"c">>
 , min => 5
 , max => 7
 }, [<<"xtcxfncccxkjzcckcbtr">> | []]} | [{#{ letter => <<"w">>
 , min => 2
 , max => 3
 }, [<<"twknmwb">> | []]} | [{#{ letter => <<"w">>
 , min => 4
 , max => 6
 }, [<<"wwcwwbwqhqkw">> | []]} | [{#{ letter => <<"x">>
 , min => 3
 , max => 10
 }, [<<"xxxxxxxxxxxxxxxxxx">> | []]} | [{#{ letter => <<"p">>
 , min => 1
 , max => 7
 }, [<<"pppppppp">> | []]} | [{#{ letter => <<"n">>
 , min => 4
 , max => 5
 }, [<<"rnnnf">> | []]} | [{#{ letter => <<"f">>
 , min => 5
 , max => 7
 }, [<<"fftfjhffff">> | []]} | [{#{ letter => <<"h">>
 , min => 8
 , max => 10
 }, [<<"hhthhhhhhzh">> | []]} | [{#{ letter => <<"s">>
 , min => 7
 , max => 17
 }, [<<"spsssshssslsssljs">> | []]} | [{#{ letter => <<"l">>
 , min => 4
 , max => 8
 }, [<<"jlltllllll">> | []]} | [{#{ letter => <<"j">>
 , min => 6
 , max => 7
 }, [<<"jjjjjwc">> | []]} | [{#{ letter => <<"f">>
 , min => 2
 , max => 18
 }, [<<"rftjffffqvffsffpfc">> | []]} | [{#{ letter => <<"w">>
 , min => 16
 , max => 17
 }, [<<"wwwwwwwwwwwwwwdsjwp">> | []]} | [{#{ letter => <<"p">>
 , min => 2
 , max => 3
 }, [<<"qtxp">> | []]} | [{#{ letter => <<"s">>
 , min => 15
 , max => 17
 }, [<<"sssssssjssssssksc">> | []]} | [{#{ letter => <<"v">>
 , min => 2
 , max => 5
 }, [<<"xvvcvmvv">> | []]} | [{#{ letter => <<"x">>
 , min => 3
 , max => 13
 }, [<<"xxvxxsxxxmhjtx">> | []]} | [{#{ letter => <<"z">>
 , min => 6
 , max => 17
 }, [<<"kfzvzzmrndrbqwskz">> | []]} | [{#{ letter => <<"s">>
 , min => 2
 , max => 3
 }, [<<"xsjqx">> | []]} | [{#{ letter => <<"t">>
 , min => 17
 , max => 18
 }, [<<"tttttttttttttrtjmstj">> | []]} | [{#{ letter => <<"n">>
 , min => 1
 , max => 3
 }, [<<"nnjnn">> | []]} | [{#{ letter => <<"c">>
 , min => 3
 , max => 7
 }, [<<"lcxcvccpc">> | []]} | [{#{ letter => <<"l">>
 , min => 7
 , max => 10
 }, [<<"lllcllllll">> | []]} | [{#{ letter => <<"z">>
 , min => 1
 , max => 3
 }, [<<"zhwzjzjzw">> | []]} | [{#{ letter => <<"d">>
 , min => 8
 , max => 9
 }, [<<"gvfbkdtdn">> | []]} | [{#{ letter => <<"w">>
 , min => 5
 , max => 7
 }, [<<"smwwgfwwww">> | []]} | [{#{ letter => <<"n">>
 , min => 4
 , max => 9
 }, [<<"nclnmsnntrkmdvw">> | []]} | [{#{ letter => <<"g">>
 , min => 1
 , max => 5
 }, [<<"qfgggg">> | []]} | [{#{ letter => <<"w">>
 , min => 8
 , max => 10
 }, [<<"wwkwwbwwww">> | []]} | [{#{ letter => <<"g">>
 , min => 1
 , max => 4
 }, [<<"kfjrxgtzcwgvrqg">> | []]} | [{#{ letter => <<"f">>
 , min => 2
 , max => 9
 }, [<<"fffffffffff">> | []]} | [{#{ letter => <<"l">>
 , min => 8
 , max => 10
 }, [<<"llllllltlnl">> | []]} | [{#{ letter => <<"c">>
 , min => 2
 , max => 13
 }, [<<"cwcccccvccccccdccc">> | []]} | [{#{ letter => <<"c">>
 , min => 2
 , max => 5
 }, [<<"wczcs">> | []]} | [{#{ letter => <<"c">>
 , min => 2
 , max => 4
 }, [<<"mlxc">> | []]} | [{#{ letter => <<"v">>
 , min => 3
 , max => 4
 }, [<<"vlvvjx">> | []]} | [{#{ letter => <<"h">>
 , min => 12
 , max => 14
 }, [<<"hshhhhhhhhhhhhh">> | []]} | [{#{ letter => <<"f">>
 , min => 17
 , max => 19
 }, [<<"fffffffvffffffffffff">> | []]} | [{#{ letter => <<"m">>
 , min => 1
 , max => 7
 }, [<<"xfbmltbm">> | []]} | [{#{ letter => <<"c">>
 , min => 8
 , max => 15
 }, [<<"ccdcngpcqjscmcqk">> | []]} | [{#{ letter => <<"b">>
 , min => 6
 , max => 11
 }, [<<"fbbbbxbbbbdnj">> | []]} | [{#{ letter => <<"j">>
 , min => 13
 , max => 14
 }, [<<"nxjmwtqpjwzjcj">> | []]} | [{#{ letter => <<"t">>
 , min => 1
 , max => 4
 }, [<<"nttjt">> | []]} | [{#{ letter => <<"m">>
 , min => 11
 , max => 13
 }, [<<"mmmmmgmmmmnmw">> | []]} | [{#{ letter => <<"h">>
 , min => 6
 , max => 14
 }, [<<"zwfvkhhhhpghrh">> | []]} | [{#{ letter => <<"l">>
 , min => 8
 , max => 9
 }, [<<"nfllllllrhlllv">> | []]} | [{#{ letter => <<"q">>
 , min => 6
 , max => 10
 }, [<<"nqpqpqqqqs">> | []]} | [{#{ letter => <<"n">>
 , min => 4
 , max => 7
 }, [<<"nnnjhng">> | []]} | [{#{ letter => <<"s">>
 , min => 7
 , max => 11
 }, [<<"ssklvwsnssstxsbsr">> | []]} | [{#{ letter => <<"x">>
 , min => 3
 , max => 12
 }, [<<"hxxxxxxxxxxxxbjrc">> | []]} | [{#{ letter => <<"k">>
 , min => 3
 , max => 18
 }, [<<"kktkkkkkkxbkckcpkk">> | []]} | [{#{ letter => <<"x">>
 , min => 1
 , max => 9
 }, [<<"lxscklsfxwxbj">> | []]} | [{#{ letter => <<"z">>
 , min => 3
 , max => 4
 }, [<<"zkfm">> | []]} | [{#{ letter => <<"r">>
 , min => 3
 , max => 15
 }, [<<"rgrshbkrwmrdkrwsjdr">> | []]} | [{#{ letter => <<"r">>
 , min => 4
 , max => 5
 }, [<<"mrlrv">> | []]} | [{#{ letter => <<"h">>
 , min => 3
 , max => 4
 }, [<<"hhhg">> | []]} | [{#{ letter => <<"t">>
 , min => 2
 , max => 7
 }, [<<"hthhzbztttbt">> | []]} | [{#{ letter => <<"r">>
 , min => 4
 , max => 7
 }, [<<"rrxxrnr">> | []]} | [{#{ letter => <<"z">>
 , min => 1
 , max => 4
 }, [<<"zdzz">> | []]} | [{#{ letter => <<"g">>
 , min => 2
 , max => 4
 }, [<<"rgggggctgcjljg">> | []]} | [{#{ letter => <<"z">>
 , min => 12
 , max => 13
 }, [<<"hjtcmnbczznzz">> | []]} | [{#{ letter => <<"s">>
 , min => 1
 , max => 4
 }, [<<"ssstss">> | []]} | [{#{ letter => <<"q">>
 , min => 10
 , max => 11
 }, [<<"qwqqqqrqqtrq">> | []]} | [{#{ letter => <<"z">>
 , min => 7
 , max => 18
 }, [<<"hhzjjrzzgjhxznmkzzhz">> | []]} | [{#{ letter => <<"f">>
 , min => 4
 , max => 5
 }, [<<"flfffd">> | []]} | [{#{ letter => <<"c">>
 , min => 6
 , max => 9
 }, [<<"cdccccccwcc">> | []]} | [{#{ letter => <<"r">>
 , min => 2
 , max => 6
 }, [<<"rfrrrpr">> | []]} | [{#{ letter => <<"x">>
 , min => 4
 , max => 10
 }, [<<"xxzqxxqqxxbn">> | []]} | [{#{ letter => <<"m">>
 , min => 2
 , max => 6
 }, [<<"dsxdmmbm">> | []]} | [{#{ letter => <<"q">>
 , min => 3
 , max => 4
 }, [<<"kqqkhn">> | []]} | [{#{ letter => <<"w">>
 , min => 7
 , max => 10
 }, [<<"wwwwwswlwgrw">> | []]} | [{#{ letter => <<"t">>
 , min => 5
 , max => 11
 }, [<<"tlxljjtntmt">> | []]} | [{#{ letter => <<"v">>
 , min => 7
 , max => 11
 }, [<<"vcvvvvgvvvmvvvv">> | []]} | [{#{ letter => <<"m">>
 , min => 2
 , max => 4
 }, [<<"mmmcmd">> | []]} | [{#{ letter => <<"x">>
 , min => 10
 , max => 12
 }, [<<"lxxxxsxzxqxb">> | []]} | [{#{ letter => <<"g">>
 , min => 4
 , max => 8
 }, [<<"vmsgpdvgwldrgvw">> | []]} | [{#{ letter => <<"t">>
 , min => 11
 , max => 13
 }, [<<"ktnttftxvtttttttqqtt">> | []]} | [{#{ letter => <<"m">>
 , min => 5
 , max => 6
 }, [<<"mmztdm">> | []]} | [{#{ letter => <<"p">>
 , min => 2
 , max => 5
 }, [<<"ppppdp">> | []]} | [{#{ letter => <<"d">>
 , min => 1
 , max => 12
 }, [<<"dddddddddddcdddd">> | []]} | [{#{ letter => <<"h">>
 , min => 8
 , max => 10
 }, [<<"thzhmhhqhrhhhhm">> | []]} | [{#{ letter => <<"d">>
 , min => 2
 , max => 10
 }, [<<"dddddmdddpdd">> | []]} | [{#{ letter => <<"q">>
 , min => 8
 , max => 13
 }, [<<"qjqqrwzpqnqgkfqqhqq">> | []]} | [{#{ letter => <<"t">>
 , min => 1
 , max => 5
 }, [<<"thptxlqtt">> | []]} | [{#{ letter => <<"v">>
 , min => 4
 , max => 6
 }, [<<"nqdfvvhvvvbv">> | []]} | [{#{ letter => <<"j">>
 , min => 8
 , max => 12
 }, [<<"jjjjjkpmjjjj">> | []]} | [{#{ letter => <<"p">>
 , min => 10
 , max => 12
 }, [<<"pfpgtppppgpxpgsjpp">> | []]} | [{#{ letter => <<"v">>
 , min => 2
 , max => 6
 }, [<<"zvvtcdbbxv">> | []]} | [{#{ letter => <<"b">>
 , min => 8
 , max => 10
 }, [<<"qbmbrbsbbb">> | []]} | [{#{ letter => <<"r">>
 , min => 2
 , max => 3
 }, [<<"drxr">> | []]} | [{#{ letter => <<"s">>
 , min => 6
 , max => 7
 }, [<<"ssssssv">> | []]} | [{#{ letter => <<"v">>
 , min => 1
 , max => 2
 }, [<<"jpvvv">> | []]} | [{#{ letter => <<"r">>
 , min => 12
 , max => 14
 }, [<<"rrrrrrjrvrrtrr">> | []]} | [{#{ letter => <<"r">>
 , min => 6
 , max => 7
 }, [<<"rjscgmr">> | []]} | [{#{ letter => <<"l">>
 , min => 11
 , max => 15
 }, [<<"llhlllbkllnlzlwllp">> | []]} | [{#{ letter => <<"l">>
 , min => 6
 , max => 10
 }, [<<"lcqlllblll">> | []]} | [{#{ letter => <<"c">>
 , min => 3
 , max => 5
 }, [<<"drfvccctgv">> | []]} | [{#{ letter => <<"s">>
 , min => 1
 , max => 3
 }, [<<"sssss">> | []]} | [{#{ letter => <<"b">>
 , min => 1
 , max => 4
 }, [<<"btbsjnx">> | []]} | [{#{ letter => <<"b">>
 , min => 9
 , max => 12
 }, [<<"bbnbbbbbbbbbb">> | []]} | [{#{ letter => <<"n">>
 , min => 2
 , max => 3
 }, [<<"nknn">> | []]} | [{#{ letter => <<"f">>
 , min => 2
 , max => 8
 }, [<<"ffffffnffs">> | []]} | [{#{ letter => <<"w">>
 , min => 4
 , max => 7
 }, [<<"wwwcwww">> | []]} | [{#{ letter => <<"f">>
 , min => 7
 , max => 14
 }, [<<"mfbpkxjzprnmpnfhdb">> | []]} | [{#{ letter => <<"h">>
 , min => 4
 , max => 11
 }, [<<"hhhshhhhhhhhhhhhhh">> | []]} | [{#{ letter => <<"q">>
 , min => 6
 , max => 8
 }, [<<"hhqdrqbmvlgpwkppc">> | []]} | [{#{ letter => <<"v">>
 , min => 1
 , max => 4
 }, [<<"vvvv">> | []]} | [{#{ letter => <<"v">>
 , min => 6
 , max => 18
 }, [<<"vvvvvdvvvvvvvvvvvgvv">> | []]} | [{#{ letter => <<"b">>
 , min => 1
 , max => 3
 }, [<<"bbxcbbbbt">> | []]} | [{#{ letter => <<"t">>
 , min => 4
 , max => 5
 }, [<<"tlvhq">> | []]} | [{#{ letter => <<"n">>
 , min => 3
 , max => 8
 }, [<<"njnzfnnns">> | []]} | [{#{ letter => <<"z">>
 , min => 5
 , max => 9
 }, [<<"zpczdfwzzcxncdzz">> | []]} | [{#{ letter => <<"s">>
 , min => 9
 , max => 14
 }, [<<"qdsssfrszsrsts">> | []]} | [{#{ letter => <<"q">>
 , min => 4
 , max => 8
 }, [<<"jqpmbzjqb">> | []]} | [{#{ letter => <<"w">>
 , min => 7
 , max => 13
 }, [<<"wjwwwwwwwwxwfww">> | []]} | [{#{ letter => <<"g">>
 , min => 16
 , max => 19
 }, [<<"zggggggggggggggqggfg">> | []]} | [{#{ letter => <<"s">>
 , min => 3
 , max => 8
 }, [<<"gsgsdtdsf">> | []]} | [{#{ letter => <<"k">>
 , min => 2
 , max => 14
 }, [<<"rkbbpnpvjkvcskdx">> | []]} | [{#{ letter => <<"s">>
 , min => 4
 , max => 6
 }, [<<"xssjzvs">> | []]} | [{#{ letter => <<"j">>
 , min => 15
 , max => 16
 }, [<<"cgdjjjjfjdwjjjjs">> | []]} | [{#{ letter => <<"n">>
 , min => 3
 , max => 6
 }, [<<"nsnnnx">> | []]} | [{#{ letter => <<"x">>
 , min => 9
 , max => 10
 }, [<<"xxxxxpxxxmxx">> | []]} | [{#{ letter => <<"x">>
 , min => 7
 , max => 8
 }, [<<"xxxxxxxl">> | []]} | [{#{ letter => <<"t">>
 , min => 2
 , max => 9
 }, [<<"tjttttttmtttt">> | []]} | [{#{ letter => <<"g">>
 , min => 12
 , max => 14
 }, [<<"gggggggggsgqzgj">> | []]} | [{#{ letter => <<"c">>
 , min => 17
 , max => 19
 }, [<<"ccccccccccccccccccc">> | []]} | [{#{ letter => <<"p">>
 , min => 8
 , max => 11
 }, [<<"pppppppcpppppp">> | []]} | [{#{ letter => <<"s">>
 , min => 12
 , max => 15
 }, [<<"sssssksssssssss">> | []]} | [{#{ letter => <<"k">>
 , min => 11
 , max => 12
 }, [<<"krkkkfkktkkq">> | []]} | [{#{ letter => <<"q">>
 , min => 17
 , max => 18
 }, [<<"qqgtqwqqqqqqqqqqjqqq">> | []]} | [{#{ letter => <<"g">>
 , min => 5
 , max => 16
 }, [<<"ngrwggggkzbggjtg">> | []]} | [{#{ letter => <<"v">>
 , min => 12
 , max => 15
 }, [<<"wvvvpvvvsvvvvdpvv">> | []]} | [{#{ letter => <<"f">>
 , min => 5
 , max => 6
 }, [<<"ffqfnffffffhf">> | []]} | [{#{ letter => <<"n">>
 , min => 7
 , max => 8
 }, [<<"nbnnnncm">> | []]} | [{#{ letter => <<"p">>
 , min => 4
 , max => 7
 }, [<<"mppppvvrp">> | []]} | [{#{ letter => <<"b">>
 , min => 10
 , max => 11
 }, [<<"qbbbbbszbnbkbb">> | []]} | [{#{ letter => <<"j">>
 , min => 8
 , max => 10
 }, [<<"jjjzjjjfjj">> | []]} | [{#{ letter => <<"c">>
 , min => 3
 , max => 7
 }, [<<"cvtcccnkcvmccgccchc">> | []]} | [{#{ letter => <<"w">>
 , min => 2
 , max => 3
 }, [<<"wnzd">> | []]} | [{#{ letter => <<"d">>
 , min => 9
 , max => 10
 }, [<<"dddddddddwdldmdddddd">> | []]} | [{#{ letter => <<"b">>
 , min => 4
 , max => 6
 }, [<<"bbbdbtbb">> | []]} | [{#{ letter => <<"h">>
 , min => 2
 , max => 10
 }, [<<"hhhhhhhhhhh">> | []]} | [{#{ letter => <<"g">>
 , min => 10
 , max => 15
 }, [<<"ggckgcgmcgjgggglgdgk">> | []]} | [{#{ letter => <<"k">>
 , min => 3
 , max => 4
 }, [<<"kkgkkk">> | []]} | [{#{ letter => <<"k">>
 , min => 10
 , max => 12
 }, [<<"sfbkhzjmbkfqrtrrq">> | []]} | [{#{ letter => <<"g">>
 , min => 3
 , max => 9
 }, [<<"ggbgsgvggs">> | []]} | [{#{ letter => <<"s">>
 , min => 2
 , max => 7
 }, [<<"sshpxwjbhmz">> | []]} | [{#{ letter => <<"x">>
 , min => 6
 , max => 7
 }, [<<"xftzsrx">> | []]} | [{#{ letter => <<"k">>
 , min => 1
 , max => 6
 }, [<<"rkkkkck">> | []]} | [{#{ letter => <<"p">>
 , min => 4
 , max => 7
 }, [<<"pppjprjp">> | []]} | [{#{ letter => <<"j">>
 , min => 17
 , max => 18
 }, [<<"jjjjjjjjwjjjzkjjjrh">> | []]} | [{#{ letter => <<"p">>
 , min => 3
 , max => 9
 }, [<<"xjpptspczfx">> | []]} | [{#{ letter => <<"m">>
 , min => 12
 , max => 15
 }, [<<"mmmmmmmmmmmmmmx">> | []]} | [{#{ letter => <<"t">>
 , min => 8
 , max => 9
 }, [<<"zttttttsldtxr">> | []]} | [{#{ letter => <<"z">>
 , min => 4
 , max => 7
 }, [<<"zzzzzzzz">> | []]} | [{#{ letter => <<"v">>
 , min => 15
 , max => 18
 }, [<<"vvvvvvvvvvkvvvfvvzv">> | []]} | [{#{ letter => <<"q">>
 , min => 2
 , max => 8
 }, [<<"vmhvmqdqz">> | []]} | [{#{ letter => <<"m">>
 , min => 15
 , max => 18
 }, [<<"mhmmmmpmmmsmmnbmwmm">> | []]} | [{#{ letter => <<"h">>
 , min => 7
 , max => 16
 }, [<<"hmgwvnnvhhzfhlhqhh">> | []]} | [{#{ letter => <<"f">>
 , min => 6
 , max => 7
 }, [<<"pqpfjmhqk">> | []]} | [{#{ letter => <<"p">>
 , min => 4
 , max => 11
 }, [<<"jzpprcpcmmpb">> | []]} | [{#{ letter => <<"f">>
 , min => 9
 , max => 10
 }, [<<"fffpffffjff">> | []]} | [{#{ letter => <<"d">>
 , min => 1
 , max => 5
 }, [<<"ndtdc">> | []]} | []]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]],
  [{some, count_all(fun count_min_max/2, Data)} | [{some, count_all(fun is_in_position/2, Data)} | []]].


